Seperate user and non-user roles
opencast/opencast-admin-interface pull request #1006
Opened 2024-12-11 13:58 UTC by Arnei

Fixes #905.

Changes the access policy tab of various details modals. User roles get displayed in a seperate table from the other roles, with user name and email. This should make it more intuitive to "give someone access to a video/ series". Functionality should not change, the resulting ACLs will look the same as before.

Caveat 1:  If roles are sanitized, we cannot reliably derive the user from their user role. Therefore, this feature will be disabled if user role sanitization is enabled in Opencast. (The old admin ui allowed for sanitized roles and did some best effort guesswork to derive users from roles. Even though that approach worked for many, I'd rather not reintroduce such brittle code here.)

Caveat 2: I did not find a performant way to query for user information for each and every user. Therefore, if there are upwards of multiple thousands of users, the access policy tab will take several seconds to load.

**Requires backend changes. TODO: Link backend PR**

### How to test this patch

Install the backend PR in your Opencast. Run this PR against your Opencast, like so `PROXY_TARGET=http://localhost:8080 npm start`. The `sanitize` flag can be found in your Opencast configuration files in `etc/org.opencastproject.userdirectory.UserIdRoleProvider.cfg`.

Screenshots:
![Bildschirmfoto vom 2024-12-11 14-51-03](https://github.com/user-attachments/assets/3b1c988e-e8d2-4e87-ac5d-6538162b4d09)

![Bildschirmfoto vom 2024-12-11 14-52-56](https://github.com/user-attachments/assets/621a7730-1989-46c5-9dc7-83059821b044)

2024-12-19 10:40 UTC, snoesberger commented
I have tested this PR together with https://github.com/opencast/opencast/pull/6382 and have a few remarks.

- With the implementation in the old admin UI, we had the ability to hide either the non-user or the user role part from users.   
  This was possible with the following roles:
  - ROLE_UI_SERIES_DETAILS_ACL_NONUSER_ROLES_VIEW
  - ROLE_UI_EVENTS_DETAILS_ACL_NONUSER_ROLES_VIEW
  - ROLE_UI_SERIES_DETAILS_ACL_USER_ROLES_VIEW
  - ROLE_UI_EVENTS_DETAILS_ACL_USER_ROLES_VIEW

  These roles don't have any effect in the new admin UI. In our case, users are only allowed to add user roles. So it's important to us that users don't have the ability to change non-user roles.

- When I add a new role, only the role ID is displayed in the dropdown for selection. In the case of user roles, this makes it difficult to know which user the ID represents. It would be better if the name and email address were displayed in the dropdown. When a role is selected, the name and email address are already displayed.

![grafik](https://github.com/user-attachments/assets/eccf53d2-7080-4290-a223-2a95a4e0d01f)

2024-12-19 10:48 UTC, Arnei commented
Thanks for testing, will look into these issues!

2024-12-19 14:08 UTC, Arnei commented
Both issues should now be fixed.

2025-01-14 17:20 UTC, gregorydlogan commented
Should an event with ROLE_USER_x be visible to user x?  I would, perhaps naively, assume that if I give a user read and/or write that they'd be able to see it in the admin UI...

Otherwise works correctly.

2025-01-15 08:05 UTC, Arnei commented
Could you specify what exactly is different from how you expect it? Which combination of role and actions does not do what you would think it do?

2025-01-16 15:41 UTC, snoesberger commented
Thanks @Arnei for addressing my [comments](https://github.com/opencast/opencast-admin-interface/pull/1006#issuecomment-2553384217).
I'm now able to hide the non-user roles in the event/series modal and I now have the proper user name and email to choose from. But I did also found some additional problems:
- When I create a new event, the Access Policy tab to add roles is displayed even though the user hasn't assigned ROLE_UI_EVENTS_DETAILS_ACL_NONUSER_ROLES_VIEW, ROLE_UI_EVENTS_DETAILS_ACL_USER_ROLES_VIEW and/or ROLE_UI_EVENTS_DETAILS_ACL_EDIT:
![grafik](https://github.com/user-attachments/assets/e134ce5f-2ce8-4174-82a7-2b01ea0bb249)
- In the dropdown to add a new user role, I can only search for the user role ID. It would be much more convenient if I could search by name or email:
![grafik](https://github.com/user-attachments/assets/671b3b05-211a-4631-ae8f-d1455f47317b)

2025-01-17 08:47 UTC, Arnei commented
> When I create a new event, the Access Policy tab to add roles is displayed even though the user hasn't assigned ROLE_UI_EVENTS_DETAILS_ACL_NONUSER_ROLES_VIEW, ROLE_UI_EVENTS_DETAILS_ACL_USER_ROLES_VIEW and/or ROLE_UI_EVENTS_DETAILS_ACL_EDIT

To make sure I understand you correctly: If the user does not have any of the roles mentioned above, the "Access Policy" tab should not be displayed at all. For example in your screenshot, the user would go from "Processing" straight to "Summary". Is that right? What roles should the event have in that case?

I would be tempted to leave fixing that to a different PR, since for me this raises questions about what the role `ROLE_UI_EVENTS_DETAILS_ACL_EDIT` means, but also about what the role `ROLE_UI_EVENTS_DETAILS_ACL_VIEW` means. At least the more specific roles `ROLE_UI_EVENTS_DETAILS_ACL_USER_ROLES_VIEW` and `ROLE_UI_EVENTS_DETAILS_ACL_NONUSER_ROLES_VIEW` are working as intended?

2025-01-17 10:41 UTC, snoesberger commented
> To make sure I understand you correctly: If the user does not have any of the roles mentioned above, the "Access Policy" tab should not be displayed at all. For example in your screenshot, the user would go from "Processing" straight to "Summary". Is that right? What roles should the event have in that case?

Yes, the user would go from "Processing" straight to "Summary". In our case we have the ACL merge mode "actions" active, this means the roles for the series are valid for such an event (and the series is mandatory for each event).


> I would be tempted to leave fixing that to a different PR, since for me this raises questions about what the role `ROLE_UI_EVENTS_DETAILS_ACL_EDIT` means, but also about what the role `ROLE_UI_EVENTS_DETAILS_ACL_VIEW` means. At least the more specific roles `ROLE_UI_EVENTS_DETAILS_ACL_USER_ROLES_VIEW` and `ROLE_UI_EVENTS_DETAILS_ACL_NONUSER_ROLES_VIEW` are working as intended?

Personally, I see the purpose of the different roles as follows:

- **ROLE_UI_EVENTS_DETAILS_ACL_VIEW**: The "Access Policy" tab in the create or edit dialog is displayed to the user. Without the roles ROLE_UI_EVENTS_DETAILS_ACL_USER_ROLES_VIEW and ROLE_UI_EVENTS_DETAILS_ACL_NONUSER_ROLES_VIEW only the "Templates" dropdown is displayed to the user. The user can't edit the ACLs.
- **ROLE_UI_EVENTS_DETAILS_ACL_EDIT**: The user is allowed to edit the ACLs of an event. Without the roles ROLE_UI_EVENTS_DETAILS_ACL_USER_ROLES_VIEW and ROLE_UI_EVENTS_DETAILS_ACL_NONUSER_ROLES_VIEW only the "Template" can be changed by the user.
- **ROLE_UI_EVENTS_DETAILS_ACL_USER_ROLES_VIEW**: The user roles part in the "Access Policy" tab in the create or edit dialog is displayed to the user. If the user has ROLE_UI_EVENTS_DETAILS_ACL_EDIT assigned, they are also allowed to edit the user roles.
- **ROLE_UI_EVENTS_DETAILS_ACL_NONUSER_ROLES_VIEW**: The non-user roles part in the "Access Policy" tab in the create or edit dialog is displayed to the user. If the user has ROLE_UI_EVENTS_DETAILS_ACL_EDIT assigned, they are also allowed to edit the non-user roles.

For us, the split view for ACLs only makes sense if we can hide the non-user roles part in both the create and edit dialog. So I'd prefer to have the ACL view roles issue fixed in this PR. But if it is much easier for you to address this in another PR, then go ahead.

2025-01-17 11:34 UTC, Arnei commented
Thanks for the very detailed explanation on the roles, that helped me a lot. I made a change so that the user requires the role "ROLE_UI_EVENTS_DETAILS_ACL_VIEW" to see the "Access Policy" step in the "Create Event" modal. This should work the default merge mode as well, and result in the other roles working as intended. Please test again.

> In the dropdown to add a new user role, I can only search for the user role ID. It would be much more convenient if I could search by name or email:

Searching should now work as intended.

2025-01-31 10:57 UTC, Arnei commented
That does indeed sound like it is not caused by this PR. In the interest of getting this PR merged, do you think the bug you found should be handled in a separate issue/PR?

2025-02-04 12:02 UTC, snoesberger commented
I'm not sure if this is relevant to this issue, but I wanted to mention it here to avoid running into the same problem with the new admin ui:

We have just upgraded our production environment to OC 16, with the old admin UI as default, and ran into the following problem with the old admin UI https://github.com/opencast/opencast/issues/5469. This problem only appears if you have a certain number of accounts in the system. We did not see the problem in our test environment with fewer users/accounts. To solve the problem we have built our own old admin UI without the PRs mentioned in https://github.com/opencast/opencast/issues/5469. My question now is, do we risk running into the same problems with this PR or does the new admin UI handle it completely differently?

2025-02-05 08:40 UTC, Arnei commented
> I'm not sure if this is relevant to this issue, but I wanted to mention it here to avoid running into the same problem with the new admin ui:
> 
> We have just upgraded our production environment to OC 16, with the old admin UI as default, and ran into the following problem with the old admin UI [opencast/opencast#5469](https://github.com/opencast/opencast/issues/5469). This problem only appears if you have a certain number of accounts in the system. We did not see the problem in our test environment with fewer users/accounts. To solve the problem we have built our own old admin UI without the PRs mentioned in [opencast/opencast#5469](https://github.com/opencast/opencast/issues/5469). My question now is, do we risk running into the same problems with this PR or does the new admin UI handle it completely differently?

The new admin ui handles this completely differently, so the issue you linked should not be a problem here at all.

2025-02-07 14:44 UTC, snoesberger commented
> Thanks for the very detailed explanation on the roles, that helped me a lot. I made a change so that the user requires the role "ROLE_UI_EVENTS_DETAILS_ACL_VIEW" to see the "Access Policy" step in the "Create Event" modal. This should work the default merge mode as well, and result in the other roles working as intended. Please test again.
> 
> > In the dropdown to add a new user role, I can only search for the user role ID. It would be much more convenient if I could search by name or email:
> 
> Searching should now work as intended.

Thanks @Arnei! The searching in the dropdown and the different ACL roles are now working as intended.

However, I have found some other problems with the template function.
- The configuration in the list provider config file `acl.default.create.properties` regarding the ACL templates isn't taken into account. Even though I added the following configuration, the user roles (ROLE_USER_*) are removed when I change the template in the UI:
```
# When switching to a new template, all roles that don't belong to the new template are removed
# To keep roles between template switches, specify role prefixes below
# Example: ROLE_AAI_USER_,ROLE_ADMIN
# Default: None
keep_on_template_switch_role_prefixes=ROLE_USER_,ROLE_ADMIN
```

- The ACL templates are not recognised. The template dropdown always shows "select a template", even though the event or series has the roles assigned as defined in a template. In the following case, the "authenticated" template should be pre-selected:
![grafik](https://github.com/user-attachments/assets/902cbc16-acc5-43d8-8ea2-212dfd0451e3)
This is especially important if the user doesn't have permission to see the non-user roles. The user has no idea which template is assigned to the series/event:
![grafik](https://github.com/user-attachments/assets/d1cde656-6444-4e45-851a-45adb4902175)

The desired behavior would be for the UI to check if the assigned non-user roles correspond to a template (ignoring all user roles and other roles defined in `acl.default.create.properties`). If so, the corresponding template is pre-selected in the template dropdown. If not, the dropdown will say "select a template". This was already the behavior in the old admin interface.

2025-02-11 08:43 UTC, Arnei commented
The issue with `keep_on_template_switch_role_prefixes` should now be fixed, thanks for reporting that.

2025-02-11 08:57 UTC, Arnei commented
Regarding recognizing ACL templates: Was that ever a feature in a the old admin ui? I did take a look but could not find code that would do such a thing.

There are also a couple of things to consider.
- When should a template be recognized?
  - Once, When the "Create new Event/Series" modal is opened? Seems reasonable, but might not be useful?
  - When changes are made to roles? Would this be confusing?
- This feature is basically best effort guessing. There is no guarantee that the intended template will be selected, should they share the same non-user roles.
- A template may also have user roles. In case a template is detected, but the current user roles are different, what should happen when that template is selected again in the dropdown? Should the user roles change, would that be confusing?

2025-02-11 15:20 UTC, snoesberger commented
> Regarding recognizing ACL templates: Was that ever a feature in a the old admin ui? I did take a look but could not find code that would do such a thing.
> 
> There are also a couple of things to consider.
> 
>     * When should a template be recognized?
>       
>       * Once, When the "Create new Event/Series" modal is opened? Seems reasonable, but might not be useful?
>       * When changes are made to roles? Would this be confusing?
> 
>     * This feature is basically best effort guessing. There is no guarantee that the intended template will be selected, should they share the same non-user roles.
> 
>     * A template may also have user roles. In case a template is detected, but the current user roles are different, what should happen when that template is selected again in the dropdown? Should the user roles change, would that be confusing?
> 
> 
> For the record, I'm not against this, I'm just musing about considerations for what the most useful and least error prone way of implementing this would be.

I'll try to explain (hopefully) more clearly how I think this should work. If it is still not clear to you, we can also have a quick call and I can show you directly on our system what I mean.

Most importantly, the template should be recognized when a user opens the modal of an existing event/series. The user should be able to check if the actual roles assigned to the event/series match a template (especially if they don't have the right to see/modify the non-user roles directly). This detection must also take into account the `keep_on_template_switch_role_prefixes' parameter. More specifically, you take all the roles assigned to an event/series and remove all the roles with the prefixes configured with the `keep_on_template_switch_role_prefixes' parameter. You compare this set of roles to the roles of the templates, if a template matches the set of roles then you have the matching template which will be displayed in the dropdown. If there is no match, no selection is made in the dropdown.

2025-02-13 14:45 UTC, Arnei commented
Thanks for the additional explanation. I was able to find how the it was done in the old admin ui, and recreated that behaviour here. It should behave like you described, with the exception that it does not respect `keep_on_template_switch_role_prefixes`, but instead respects `match.managed.acl.role.prefixes` from `etc/org.opencastproject.adminui.impl.AdminUIConfiguration.cfg`. `match.managed.acl.role.prefixes` can be configured the same way as `keep_on_template_switch_role_prefixes` which should lead to the desired behaviour.

2025-02-14 14:48 UTC, snoesberger commented
Thanks once more for the improvements you made @Arnei! Sorry, I hadn't kept in mind that there is this second config parameter `match.managed.acl.role.prefixes` that affects the behavior of the UI.

The recognition of the templates works better now, but I still found some issues:

- If I don't put a "," at the end of the `match.managed.acl.role.prefixes` parameter, the last prefix is not taken into account when recognizing a template. For example, in the case of `match.managed.acl.role.prefixes=ROLE_USER_,ROLE_ADMIN,ROLE_GROUP_IGNORE`, if a role with the prefix `ROLE_GROUP_IGNORE` is assigned to the series, no template will be recognized. Is this intentional? For the `keep_on_template_switch_role_prefixes` parameter this is not the case and is actually counterproductive. If I add a "," to the `keep_on_template_switch_role_prefixes` parameter, all roles are kept when I switch templates.

- A user needs the ROLE_UI_SERIES_DETAILS_TOBIRA_EDIT and ROLE_UI_SERIES_DETAILS_TOBIRA_VIEW roles (among others) to be able to create a new series even though Tobira isn't configured. If these roles are not assigned to the user, the browser screen turns white after selecting the ACLs and clicking the "Next" button during the series creation process. In the browser console I can see that the UI accesses `/admin-ng/series/new/tobira/page?path=` and gets a "403 Forbidden" response. If the user has the Tobira roles assigned, the same request answers with "503 Tobira is not configured" and the series can be created. In my opinion, it should not be necessary for the user to have these Tobira roles assigned in order to create a series.

2025-02-17 08:52 UTC, Arnei commented
Thanks again for the extensive testing. 

> A user needs the ROLE_UI_SERIES_DETAILS_TOBIRA_EDIT and ROLE_UI_SERIES_DETAILS_TOBIRA_VIEW roles [...]

I agree that tobira roles should not be necessary if there is not tobira, but I cannot reproduce your error. I assume it is related to another bug, where the clicking on "next" in a create modal would open a tab that should have been hidden (e.g. the tobira tab would be opened even if not tobira was configured). Recently some PRs like #856 that help with this bug were merged, so if we're lucky this error is fixed already.

2025-02-17 10:51 UTC, Arnei commented
Regarding your second point, I agree that having Tobira roles should never be necessary to create a series, much less cause the app to crash. Unfortunately, this is not quite easy for me to solve, I'll have to consult with our local Tobira experts for that.

2025-02-25 15:37 UTC, Arnei commented
https://github.com/opencast/opencast-admin-interface/pull/1122 should resolve the second problem.

2025-03-10 17:36 UTC, marwyg requested changes
I have looked through the code. Apart from the one uncertainty that I noticed, the code looks okay to me so far.

2025-03-11 07:41 UTC, Arnei commented on src/components/shared/DropDown.tsx
> +	improvePerformanceExperimental = false,
This is some performance testing stuff that has proven beneficial for the intended use-case (filtering), but I am unsure if it may negatively impact performance in other cases. That's why I turned it into a toggle instead of it being always on.

2025-03-11 10:22 UTC, marwyg approved these changes
My only concern was addressed. I talked to @snoesberger today and he would like to test this PR again. 

From the code perspective I have nothing to complain.

2025-03-14 12:33 UTC, snoesberger commented
I retested @Arnei's last commit and the dropdown provides now correctly only user roles in the user role section and non-user roles in the non-user roles section again. The user names are also nicely rendered again. Thanks for fixing that!

During my testing I found another small issue. In the "Access Policy" step of the create event/series dialogue, the user role is first displayed in the non-user section:
![grafik](https://github.com/user-attachments/assets/bb49240e-27b0-49ff-abcb-5163d01511f7)

Only after choosing a template the user role is correctly displayed in the user section.

2025-03-17 11:23 UTC, Arnei commented
Thanks for catching that. The user role that is automatically added to the ACL for events and series should now be displayed as a user role once again.

2025-03-24 12:44 UTC, marwyg commented
I did a second look at the code, because there were changes since last time. But I still have nothing to complain about.

As far as I'm concerned, the PR can go out like this, provided the backend PR has been completed: https://github.com/opencast/opencast/pull/6382.

2025-03-27 15:24 UTC, snoesberger commented
> Thanks for catching that. The user role that is automatically added to the ACL for events and series should now be displayed as a user role once again.
> 
> ![Bildschirmfoto vom 2025-03-17 12-24-34](https://private-user-images.githubusercontent.com/14070005/423448515-2556b7c1-73e6-4bc3-8d1b-8fd0e810394b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDMwODgzODksIm5iZiI6MTc0MzA4ODA4OSwicGF0aCI6Ii8xNDA3MDAwNS80MjM0NDg1MTUtMjU1NmI3YzEtNzNlNi00YmMzLThkMWItOGZkMGU4MTAzOTRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMzI3VDE1MDgwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRjMjEyYTU5OTIxMDBhZTZlMmFkMDFiYjc5MjAyMDU1ZTYwZmExOTIwZmUzMWYyN2JhMjhmMDM0MWNkZDEzZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.bCh-_aAWa63aynleatnuQJbQ03_4QzopUWUw7D0XUUg)

Thanks, I can confirm that this working now as expected.

2025-05-14 00:55 UTC, gregorydlogan requested changes
Urgh.  So fresh build of 17.x+relevant PR and this PR + a delete of package-lock.json:

![image](https://github.com/user-attachments/assets/bd10e3fb-044d-4b93-9be6-3c8a3b43b97c)
- I can't see the test user I created when trying to upload an event
  - I also don't see any REST query which looks like a 'fetch-all-users' request.  Nor does Chrome find my test user when I search for it in the requests log.
  - The user's role does appear in the bottom set of roles, regardless of `sanitize` setting - so the user definitely exists at least :)
 - The bottom set of role definitions needs a better title than 'Details' :)
 - The ACL templates just straight up don't work at all, 404ing looking for `/admin-ng/users/usersforroles.json`

It's unclear to me which of these might be affected by the current bugbash work.

2025-05-14 12:25 UTC, Arnei commented
*Now* it has been affected by the bugbash. Not in a way that would explain your problems though.

2025-05-14 13:49 UTC, snoesberger commented
> Would you help me out with a suggestion? I agree that "Details" is not a very useful descriptor here, but I'm struggling to come up with something better.

In the old admin UI, this section was called "Non-user Roles." To be consistent with the naming of the user section, we could  name it "Roles and Groups Authorized for the Event"? Though technically, we have user roles in the user section... However, end users will not be aware of that.

2025-05-14 15:20 UTC, gregorydlogan commented
My test user's `ROLE_USER_test` exists in the bottom section, but anything would be better than just 'Details' :)

2025-05-15 08:28 UTC, Arnei commented
You'll have to show me your setup sometime Greg. It kinda sounds like your admin interface is not pointing at the correct Opencast, but also like there is more going on.

2025-05-15 13:30 UTC, snoesberger commented
For me it works as well:
![grafik](https://github.com/user-attachments/assets/9d8a37fe-ef43-4f6f-b6cc-4eb3ad2b41bf)


I did use a local OC build based on r/17.x incl. https://github.com/opencast/opencast/pull/6382 (but I also had to recreate package-lock.json for the admin UI).

2025-05-16 20:29 UTC, gregorydlogan commented
I... don't get what I was doing wrong, but after git clean of *literally everything* it works fine.

2025-05-16 20:30 UTC, merged