Show conflicting scheduling events for new events
opencast/opencast-admin-interface pull request #220
Opened 2023-11-03 11:37 UTC by Arnei

Fixes #132

When trying to schedule a new event, there already is a notification if the new event would cause a conflict with an already scheduled event. However, it would not tell you with which event, leaving you guessing on how to resolve the conflict. This display the conflicting event, same as when trying to reschedule an event in the event details.

2024-01-16 23:49 UTC, gregorydlogan commented
Testing this I saw:
- False positive warnings where it said I had a conflict when I hadn't scheduled anything at all yet
- The warning did not go away when the desired time changed
  - The false positive might be responsible for this too, manually closing the warning made it go away for a screen or two, but then it'd be back
 - Uncaught Runtime Errors about state mutations.  I see this one a lot, across all reviews.

2024-01-17 08:29 UTC, Arnei commented
Thanks for the review, will look into it.

2024-01-17 13:34 UTC, Arnei commented
> Uncaught Runtime Errors about state mutations. I see this one a lot, across all reviews.

If it happens across many different PRs, it is likely it's own issue?

2024-02-22 20:20 UTC, gregorydlogan requested changes

2024-02-22 20:20 UTC, gregorydlogan commented on app/src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
> +              conflicts.length > 0 && (
The main conflict blob is appearing, but this doesn't ever get added to the DOM.  Searching for `scheduling-conflict` doesn't find any elements.

2024-02-29 13:57 UTC, Arnei commented on app/src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
> +              conflicts.length > 0 && (
"Works on my machine":
![Bildschirmfoto vom 2024-02-29 14-55-32](https://github.com/opencast/opencast-admin-interface/assets/14070005/bb835f23-3f8f-4349-acea-5aa47995179d)

Maybe you could share more details on how exactly you are testing this?

2024-03-01 14:51 UTC, Arnei commented on app/src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
> +              conflicts.length > 0 && (
Well, i dare say your normal is not expected behaviour. :D

Could it be that proxying to docker is somehow the problem? Seems to be main difference between our systems, and that proxy is a fickle thing.

2024-05-24 20:48 UTC, merged