Fix mixed_text metadata fields without collection
opencast/opencast-admin-interface pull request #232
Opened 2023-12-14 16:26 UTC by KatrinIhler

We have disabled the listproviders for some mixed_text fields in the episode and series metadata for performance reasons, meaning that those fields don't have a collection, which is a valid config for the old Admin UI. However, this currently breaks the new one:
![image](https://github.com/opencast/opencast-admin-interface/assets/11960278/42f47227-3b24-4ada-9a7b-b88e6e2242fe)

Simply checking if field.collection is defined before checking its length should fix this.

Warning: I didn't test this because I didn't want to deal with figuring out how to do this against my local Opencast instance. But this is simple enough, so it should be fine...right?

2023-12-15 11:09 UTC, Arnei commented
Could you share what config(s) you used to trigger the error?

Are the performance issues caused by the new admin ui? Want to open an issue for that?

> Edit: I'm also unsure which branch to point this at to get it into Opencast as soon as possible, maybe you can advise me on that?

You chose the correct branch. There is also no fixed release schedule atm, you can basically cut a release whenever.

2023-12-15 11:49 UTC, KatrinIhler commented
> Could you share what config(s) you used to trigger the error?

Sure! Just comment out the listprovider for at least one field with type `mixed_text` in either `org.opencastproject.ui.metadata.CatalogUIAdapterFactory-episode-common.cfg` or `org.opencastproject.ui.metadata.CatalogUIAdapterFactory-series-common.cfg` to trigger the error for events and series details respectively. Example:

```
# Presenters
property.presenters.inputID=creator
property.presenters.label=EVENTS.EVENTS.DETAILS.METADATA.PRESENTERS
property.presenters.type=mixed_text
property.presenters.readOnly=false
property.presenters.required=false
# property.presenters.listprovider=CONTRIBUTORS
property.presenters.order=7
```

> Are the performance issues caused by the new admin ui? Want to open an issue for that?

Nope, that's Opencast's fault, and it's a known problem with requesting all users.

2023-12-15 11:51 UTC, KatrinIhler commented
Oh, and I also just realized I didn't describe the error correctly: If you open either series or event details, the whole Admin UI turns white. :D

2023-12-15 12:55 UTC, Arnei requested changes
Makes sense to me and works. Below is a suggestion that should be functionally equivalent, but less code :D

2023-12-15 14:37 UTC, KatrinIhler commented on app/src/components/events/partials/ModalTabsAndPages/DetailsMetadataTab.tsx
>  																	field.collection.length !== 0 ? (
Julian already suggested this to me, but I didn't dare try that without testing. But if you say so... ;)

2023-12-15 14:40 UTC, Arnei approved these changes

2023-12-18 08:20 UTC, Arnei commented
Actually wait a sec, the same error occurs in `NewMetadataPage.tsx` (line 44). Other Metadata related tsx files seems to be fine.

2023-12-19 11:58 UTC, KatrinIhler commented
> Actually wait a sec, the same error occurs in `NewMetadataPage.tsx` (line 44). Other Metadata related tsx files seems to be fine.

Good catch. Actually affects the extended metadata as well. But now I think I got everything. :D Again: I didn't test this, especially with the new syntax using ?.

2023-12-19 13:14 UTC, Arnei approved these changes

2023-12-19 16:23 UTC, merged