Fix unique key issue in WizzardStepper
opencast/opencast-admin-interface pull request #386
Opened 2024-05-09 01:38 UTC by ziegenberg

Fixes a web console complaint about missing unique keys in the WizzardSteppers. I deem using .filter() a nicer solution than a ternary operator that checks if the hidden property of the current label object is false and rendering an empty fragment. This is probably also what made the console unhappy.

2024-05-14 11:59 UTC, Arnei requested changes
This seems to break whatever arcane magic the WizardStepper is using. In the image below I'm in the "source" step, but the WizardStepper believes me to be in the "asset upload" step.

![Bildschirmfoto vom 2024-05-14 13-57-06](https://github.com/opencast/opencast-admin-interface/assets/14070005/464ec24f-8b24-4eea-9d10-21da0197d0d0)

2024-05-24 15:45 UTC, ziegenberg commented
Rebased.

2024-07-11 07:46 UTC, Arnei commented
Can't reproduce the web console warning anymore, so we can probably close this. @ziegenberg, what say you?

2024-07-11 13:40 UTC, ziegenberg commented
Yeah, it was fixed in another way. So, closing it is.

2024-07-11 13:40 UTC, closed without merging