dont display ui when logged out
opencast/opencast-admin-interface pull request #401
Opened 2024-05-17 06:44 UTC by schuettloeffel-elsa

Closes #397

2024-05-17 06:59 UTC, schuettloeffel-elsa commented
Ah, maybe better redirect to the loginpage instead..

2024-05-21 16:01 UTC, gregorydlogan requested changes

2024-05-21 16:01 UTC, gregorydlogan commented on app/src/slices/healthSlice.ts
>  	const res = await axios.get<FetchHealthStatusResponse>("/services/health.json");
You want to parse `/info/me.json` and look for `ROLE_ADMIN_UI` in the roles field.  It's possible to have an admin ui user who can see the UI, but *not* the health metrics.

2024-05-22 11:41 UTC, schuettloeffel-elsa commented on app/src/slices/healthSlice.ts
>  	const res = await axios.get<FetchHealthStatusResponse>("/services/health.json");
Ok thanks, I gave it another try

2024-05-24 08:53 UTC, schuettloeffel-elsa commented on app/src/slices/healthSlice.ts
>  	const res = await axios.get<FetchHealthStatusResponse>("/services/health.json");
Hei @gregorydlogan can you have another look at the new draft?

2024-05-24 20:57 UTC, gregorydlogan commented
This looks reasonable to me, haven't had a chance to test.  Take this out of draft mode when you're ready and we can take a look.

2024-06-04 20:55 UTC, merged