Better naming for Crowdin workflows
opencast/opencast-admin-interface pull request #407
Opened 2024-05-21 16:59 UTC by lkiesow

Let all GitHub Actions workflow definitions for Crowdin…

- have a filename starting with `crowdin-…`
- Have a name starting with `Crowdin » `

2024-05-21 17:13 UTC, ziegenberg approved these changes
Looks good to me.

2024-05-22 13:00 UTC, ziegenberg requested changes
The line
```
crowdin download --config .crowdin.yaml -b admin-ui-picard
```
probably also needs changing, and the branch name updated to `main`.

That's what the last GHA error suggest: https://github.com/opencast/opencast-admin-interface/actions/runs/9153874134/job/25163529960

2024-05-23 15:45 UTC, lkiesow commented
Fixed conflicts and branch name

2024-05-24 14:05 UTC, ziegenberg requested changes

2024-05-24 14:05 UTC, ziegenberg commented on .github/workflows/crowdin-download-translations.yml
>            echo '" ]' >> locales.json
Do we need this step? Isn't the list of languages configured here `src/i18n/languages.ts`?

2024-05-24 14:06 UTC, ziegenberg commented on .github/workflows/crowdin-download-translations.yml
>            git add /src/i18n/org/opencastproject/adminui/languages/
Should we have those absolute file paths here? Same with the next step

2024-05-24 20:53 UTC, gregorydlogan commented on .github/workflows/crowdin-download-translations.yml
>            git add /src/i18n/org/opencastproject/adminui/languages/
The upstream project uses `git commit -a` here.  Unsure which is less safe :D

2024-05-24 21:02 UTC, ziegenberg commented on .github/workflows/crowdin-download-translations.yml
>            git add /src/i18n/org/opencastproject/adminui/languages/
I'm just not sure if an absolute file path would work or if this should be relative to the current working directory...

2024-05-28 15:35 UTC, ziegenberg commented on .github/workflows/crowdin-download-translations.yml
>            git add /src/i18n/org/opencastproject/adminui/languages/
@lkiesow, could you quickly look at this? Then, we could merge it right after.

2024-05-28 16:31 UTC, ziegenberg approved these changes

2024-05-28 16:31 UTC, ziegenberg commented
Looking good now!

2024-05-28 16:32 UTC, merged