Correctly import zh-CN and zh-TW
opencast/opencast-admin-interface pull request #457
Opened 2024-05-24 12:34 UTC by ziegenberg

This fixes the garbled use of zh-CN and zh-TW. We used the flag from the one, the description of the other and only used one, so somehow got it mixed up.

The strings 简体中文 and 繁體中文 were approved by a native speaker. We shouldn't be stepping on anybody's toes too badly ...

2024-05-24 13:41 UTC, ziegenberg commented
@JulianKniephoff would you approve the changes in b817e4c345db8c28df7b26c431c20a07c5eea143?

2024-05-27 14:21 UTC, JulianKniephoff reviewed
The code changes I gladly approve.

Regarding the language stuff I have some thoughts, but obviously I'm not a native, so take this with a grain of salt. I did some research right now, but of course I'm not immersed in these cultures, and know very little about conventions and idiomatic use of these languages/terms. However, while I don't want to question any one person in particular, I **do** want to put out there that being a native does not necessarily qualify someone to answer these questions. Natives can be "wrong" about their languages, especially in a situation that's politically loaded like this one. Because remember, too, that we are dealing with **two** languages here, but see also below. Anyway:

First of all, by now we should all know that [flags aren't langauges](https://www.flagsarenotlanguages.com). Of course whether or not we want to keep the flags is a bigger discussion outside the scope of this PR. I just wanted to mention it for completeness.

What we **should** discuss here is what our translations actually represent, especially when talking about variants like this. Officially `zh_CN` is Chinese as spoken/written in the PRC, and `zh_TW` is Chinese as used in Taiwan. This is also what the flags suggest. I don't know and can't really verify whether that's what's in the translation files, but as far as I'm concerned that is what we are intending to provide here: A localization that's appropriate for mainland China and another one that's appropriate for Taiwan. And people who don't fall directly into these categories probably know/have a preference about which one of those they should pick. (Same way as we don't have a Canadian English translation, but @gregorydlogan still has an opinion about which one he wants.)

And it is true (generally, probably simplifying a lot here) that that maps to simplified vs. traditional Chinese writing, but that's only part of it. However, if I understand correctly, 简体中文 and 繁體中文 specify exactly that, simplified and traditional Chinese **writing**. So are our two Chinese translations just the same texts but written in different writing systems? I don't think so. And even if, mapping that to flags would definitely be wrong then, and also I think it's kind of weird to have that while other translations have a rather clear connection to some territory.

Anyway, these specific terms might be weird for another reason:

> The government of Taiwan officially refers to traditional Chinese characters as 正體字; 正体字; zhèngtǐzì; 'orthodox characters'.[[9]](https://en.wikipedia.org/wiki/Traditional_Chinese_characters#cite_note-9) This term is also used outside Taiwan to distinguish standard characters, including both simplified, and traditional, from other [variants and idiomatic characters](https://en.wikipedia.org/wiki/Variant_Chinese_characters).[[10]](https://en.wikipedia.org/wiki/Traditional_Chinese_characters#cite_note-10) Users of traditional characters elsewhere, as well as those using simplified characters, call traditional characters 繁體字
> —<cite>[Wikipedia](https://en.wikipedia.org/wiki/Traditional_Chinese_characters#Terminology)</cite>

So I think it's weird to use 繁體中文 as the self-description of the `zh_TW` locale. IIUC it should be 正體中文, but what I'm really getting at is that we maybe should use the names these territories use for their own language, instead of just their writing system. Which, AFAIK, would be either 中文 for both, or 汉语 and 漢語 for PRC and Taiwan respectively.

TL;DR I propose changing this:

<img width="178" alt="image" src="https://github.com/opencast/opencast-admin-interface/assets/123272/b974025c-5829-417b-888e-182254eba937">

to either this (note again the similarity to English):

<img width="197" alt="image" src="https://github.com/opencast/opencast-admin-interface/assets/123272/0b7ef357-bc94-40e8-9d88-373c4cfca804">

or this:

<img width="195" alt="image" src="https://github.com/opencast/opencast-admin-interface/assets/123272/d80abb63-6ef1-47ff-a2b1-610e5f2f8e53">

2024-05-28 14:25 UTC, ziegenberg commented
That's what Google offers when switching languages:
![Screenshot from 2024-05-28 16-17-15](https://github.com/opencast/opencast-admin-interface/assets/856916/f85672cc-52f3-482c-91d2-e5578af5cb84)

For traditional Chinese, they also offer a country selection:
![Screenshot from 2024-05-28 16-17-29](https://github.com/opencast/opencast-admin-interface/assets/856916/26874a98-dee1-4ee1-bbf4-207af6f51e7a)

2024-05-28 22:13 UTC, geichelberger commented
> Using 中文 for both provides the least value and the best would be to get rid of the flags all along. We could also argue why we have a German flag for the german language when there also could be a Swiss or an Australian flag used in that case...

🚫🦘

2024-05-29 08:25 UTC, ziegenberg commented
> > Using 中文 for both provides the least value and the best would be to get rid of the flags all along. We could also argue why we have a German flag for the german language when there also could be a Swiss or an Australian flag used in that case...
> 
> 🚫🦘

Autocorrection 🤨🙄🤬

2024-05-30 08:13 UTC, JulianKniephoff commented
I'm definitely in favor of removing the flags. Regarding the wording I voiced my concerns, but I don't want to block anything with them. If Google uses these terms as well, that can of course still be wrong, but so can I, and I unfortunately don't have the resources right now to get deeper into it. 🤷‍♀️

One thing I would be interested in is what language codes Google maps these strings to. 🤔

2024-05-30 14:36 UTC, ziegenberg commented
@JulianKniephoff I rebased and removed the flags. Can you have a look once more?

2024-06-03 15:57 UTC, JulianKniephoff requested changes
Some nitpicks in the code.

For everyone's convenience, this is what it looks like now:

<img width="494" alt="image" src="https://github.com/opencast/opencast-admin-interface/assets/123272/d5c8b310-4b41-49e0-9bef-dd038a9950f6">

2024-06-03 15:57 UTC, JulianKniephoff commented on tsconfig.json
> +    /* Visit https://aka.ms/tsconfig to read more about this file */
This line seems a little misplaced, both in this PR and within the file. think 🤔

2024-06-03 15:57 UTC, JulianKniephoff commented on src/components/Header.tsx
>  						{/* Click on the flag icon, a dropdown menu with all available languages opens */}
What flag icon? 😉

2024-06-03 15:57 UTC, JulianKniephoff commented on src/components/Header.tsx
> +						<div className="lang" title={t("LANGUAGE")} onClick={() => setMenuLang(!displayMenuLang)}>
I would get rid of the `title` attribute in this case, this element is now self-describing. Also, can we get rid of the `LANGUAGE` translation key then?

**OR** we use that as the text for the selector, not the selected language.

Or we use it as `alt` for a generic language selector icon, like the typical globe or the "A文" thing you see sometimes. 🤔

2024-06-04 09:15 UTC, ziegenberg commented on tsconfig.json
> +    /* Visit https://aka.ms/tsconfig to read more about this file */
I will remove it

2024-06-04 09:17 UTC, ziegenberg commented on src/components/Header.tsx
>  						{/* Click on the flag icon, a dropdown menu with all available languages opens */}
removed

2024-06-04 09:24 UTC, ziegenberg commented on src/components/Header.tsx
> +						<div className="lang" title={t("LANGUAGE")} onClick={() => setMenuLang(!displayMenuLang)}>
I would got for the third option.

2024-06-04 09:52 UTC, ziegenberg commented on src/components/Header.tsx
> +						<div className="lang" title={t("LANGUAGE")} onClick={() => setMenuLang(!displayMenuLang)}>
@JulianKniephoff which of the two icons do you prefer?

`FaGlobe from "react-icons/fa"`

![Screenshot from 2024-06-04 11-47-11](https://github.com/opencast/opencast-admin-interface/assets/856916/88066ea1-1f2e-4297-8356-3ac39086df8e)

`FaLanguage from "react-icons/fa"`

![Screenshot from 2024-06-04 11-47-38](https://github.com/opencast/opencast-admin-interface/assets/856916/0389c67c-96ac-48c3-946a-865b4c0b2903)

2024-06-04 09:54 UTC, ziegenberg commented on src/components/Header.tsx
> +						<div className="lang" title={t("LANGUAGE")} onClick={() => setMenuLang(!displayMenuLang)}>
I will leave the `title` attribute in here, as it creates a nice pop-over

![Screenshot from 2024-06-04 11-52-40](https://github.com/opencast/opencast-admin-interface/assets/856916/1e4435c8-28a0-4b5e-b60c-dfefd4f54675)

2024-06-04 14:25 UTC, lkiesow commented
The selector looks fine, except the icon which is different from all other tools we have (studio, editor, tobira) and three people told me (and I agree) that they didn't identify this as a language selector. It looks like something related to internet or network or something like that.

![Screenshot from 2024-06-04 16-06-33](https://github.com/opencast/opencast-admin-interface/assets/1008395/78e9ca20-06b7-40e2-b1f5-b11845b40474)

Can we just use what we use in the other tools?
![Screenshot from 2024-06-04 16-05-12](https://github.com/opencast/opencast-admin-interface/assets/1008395/68db975c-db49-455d-866c-2fbd162a6bb9)


Except for that, I'm fine with the new dialog.

2024-06-04 14:28 UTC, JulianKniephoff commented on src/components/Header.tsx
> +						<div className="lang" title={t("LANGUAGE")} onClick={() => setMenuLang(!displayMenuLang)}>
I think I prefer the globe in this case 🤔

2024-06-04 15:11 UTC, ziegenberg commented
> The selector looks fine, except the icon which is different from all other tools we have (studio, editor, tobira) and three people told me (and I agree) that they didn't identify this as a language selector. It looks like something related to internet or network or something like that.
> 
> 
> Can we just use what we use in the other tools? 

@lkiesow, would you be okay with the second version, like here: https://github.com/opencast/opencast-admin-interface/pull/457#discussion_r1625709840? I would stay within the same iconography, and that's currently FontAwesome5. We can change this at a later stage.

@JulianKniephoff prefers the globe.

2024-06-07 11:15 UTC, lkiesow commented
> @lkiesow, would you be okay with the second version, like here: [#457 (comment)](https://github.com/opencast/opencast-admin-interface/pull/457#discussion_r1625709840)? I would stay within the same iconography, and that's currently FontAwesome5. We can change this at a later stage.

Sorry for the late reply. Lots of other patches drawing attention ;-)
That's definitely better. But judging by your poll in Matrix, you might have already decided to go with another icon.

2024-06-11 16:34 UTC, lkiesow approved these changes

2024-06-11 16:34 UTC, merged