Replace react-script with vite
opencast/opencast-admin-interface pull request #471
Opened 2024-05-27 21:01 UTC by geichelberger

2024-05-28 09:00 UTC, geichelberger commented
Was the code necessary to deploy it like that?

2024-05-28 09:50 UTC, Arnei requested changes
Good riddance CRA, hello Vite!

Works and looks good to me, the comments below are just nitpicks, I am more than willing to approve this. Although we should still discuss if we want to get rid of the mock data. (Personally I never use it so I wouldn't mind if it was gone).

2024-05-28 09:50 UTC, Arnei commented on package.json
> +    "@types/http-proxy": "^1.17.14",
This seems to be going unused.

2024-05-28 09:50 UTC, Arnei commented on package.json
> +    "eslint-plugin-react-hooks": "^4.6.0",
Explicitly importing these seems to be unnecessary?

2024-05-28 09:50 UTC, Arnei commented on package.json
>      "@babel/preset-react": "^7.24.1",
Gettring rid of CRA should also mean that we can get rid of babel!

2024-05-28 10:30 UTC, Arnei approved these changes

2024-05-28 13:45 UTC, ziegenberg commented on README.md
> +PROXY_TARGET=http://localhost:8080 npm start
Why not leave the example with `https://develop.opencast.org` in here? It would make it easier for the testers to know what to type.

2024-05-28 13:51 UTC, geichelberger commented on README.md
> +PROXY_TARGET=http://localhost:8080 npm start
This is the example for a different target, the default is `https://develop.opencast.org`

2024-05-28 16:14 UTC, ziegenberg commented on README.md
> +PROXY_TARGET=http://localhost:8080 npm start
Ah, I overlooked the config `vite.config.ts`

2024-05-28 18:32 UTC, geichelberger commented
As the test deployments are only static files, removing the proxy should not cause any trouble.

2024-05-28 20:42 UTC, lkiesow approved these changes
Misunderstood that:
- Mock data is gone (that just needs a slight text update in #470)
- Proxy still exists
- Default target now is https://develop.opencast.org which I like since it should work for most people with the default config

2024-05-28 20:43 UTC, lkiesow commented on README.md
> +This assumes you have an internet connection to which the development server will then proxy all the backend request,
Can we explicitly state that the default proxy target is https://develop.opencast.org? That “the internet” is proceed is rather vague :grin:

2024-05-29 21:54 UTC, lkiesow commented
Since #470 got merged, can you update the test comment:

https://github.com/opencast/opencast-admin-interface/blob/ddfd555a61efcbb11f0376b07724975327657446/.github/workflows/deploy-container-image.yaml#L53-L61

This should now probably be something like:

     Run test server using develop.opencast.org as backend:
     ``` 
     podman run --rm -it -p 127.0.0.1:3000:3000 ${{ steps.meta.outputs.tags }} 
     ``` 
  
     Specify a different backend like stable.opencast.org:
     ``` 
     podman run --rm -it -p 127.0.0.1:3000:3000 -e PROXY_TARGET=https://stable.opencast.org ${{ steps.meta.outputs.tags }} 
     ```

2024-05-30 23:02 UTC, lkiesow commented
Sorry for finding another issue :see_no_evil: 

This causes the container to fail since they do not contain a browser:
```
❯ podman run --rm -it -p 127.0.0.1:3000:3000 opencast-admin-interface:6dfe2dc                                           

> admin-ui-picard@0.1.0 start
> vite

The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.

  VITE v5.2.11  ready in 207 ms

  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
node:events:497
      throw er; // Unhandled 'error' event
      ^

Error: spawn xdg-open ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
Emitted 'error' event on ChildProcess instance at:
    at ChildProcess._handle.onexit (node:internal/child_process:292:12)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn xdg-open',
  path: 'xdg-open',
  spawnargs: [ 'http://localhost:3000/' ]
}

Node.js v20.13.1
```

The vite server also listens to localhost only which does not work with the containers.

There may be a better way, but this will fix the issues:

```diff
diff --git a/Dockerfile b/Dockerfile
index 2782425b1f..1890183c3c 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -7,4 +7,5 @@ WORKDIR /admin-interface
 RUN npm ci
 
 ENV CI true
+ENV BROWSER none
 CMD [ "npm", "start" ]
diff --git a/package.json b/package.json
index 4a14ced112..c0bd48faa9 100644
--- a/package.json
+++ b/package.json
@@ -45,7 +45,7 @@
     "yup": "^1.4.0"
   },
   "scripts": {
-    "start": "vite",
+    "start": "vite --host 0.0.0.0",
     "build": "tsc && vite build",
     "serve": "vite preview",
     "test": "vitest"
```

2024-05-31 09:10 UTC, geichelberger commented
I did not alter the package.json because I would not expect vite to listen on all addresses in a dev environment. Instead, I added the host option to the `CMD` instruction.

2024-05-31 10:08 UTC, lkiesow commented
Great. Tried that but without the `--`. Didn't know that I need to separate that. Thanks. Merging…

2024-05-31 10:08 UTC, merged