Test without mocks
opencast/opencast-admin-interface pull request #483
Opened 2024-05-28 17:10 UTC by geichelberger

This change allows to configure the Axios client to use a different base
URL and set the authentication header.

NODE_ENV=development
VITE_TEST_SERVER_URL=https://development.opencast.org/
VITE_TEST_SERVER_AUTH="admin:opencast"

2024-05-29 09:09 UTC, geichelberger commented
There will be more documentation when it's ready for review. I will refactor it after https://github.com/opencast/opencast-admin-interface/pull/472 is merged,

2024-05-29 09:30 UTC, ziegenberg commented
Can the mock data be re-used for Unit and integration tests? So, should we throw it away with this PR or keep it for later use?

2024-05-29 09:50 UTC, geichelberger commented
The data is not gone. It's still in the commit history.

2024-05-30 19:08 UTC, geichelberger commented
To have data that is not used and, therefore, not maintained makes no sense. And with the argumentation that we may need it in the future, we should not remove unused stuff at all.

2024-06-04 09:33 UTC, geichelberger commented
Should we document the environment variables? They should only be used in the workflows, and the other workflow-specific variables are not documented either.

2024-06-04 21:48 UTC, gregorydlogan commented on README.md
> +NODE_ENV=development VITE_TEST_SERVER_URL="https://develop.opencast.org" VITE_TEST_SERVER_AUTH="admin:opencast" npm start
I'm not sure how common this will be, in testing against localhost I could not get this to work until I put a proxy with a wide open CORS config in between.  So `VITE_TEST_SERVER_URL="http://localhost:8080"` did *not* work, but `VITE_TEST_SERVER_URL="http://localhost" <- now with proxy!` did.  Would it be worth explaining that here, or am I sufficiently out of touch with frontend dev that this is something that's obvious?

2024-06-05 06:04 UTC, geichelberger commented on README.md
> +NODE_ENV=development VITE_TEST_SERVER_URL="https://develop.opencast.org" VITE_TEST_SERVER_AUTH="admin:opencast" npm start
I think CORS is Daily Business nowadays, and the Vite proxy would be a better fit for local scenarios.

2025-03-31 09:51 UTC, Arnei requested changes
Wow, this has been utterly forgotten >.>. Looks good to me though, just one checkstyle complaint.

2025-03-31 09:51 UTC, Arnei commented on src/index.tsx
> +	axios.defaults.headers.common['Authorization'] = import.meta.env.VITE_TEST_SERVER_AUTH && ("Basic " + window.btoa(import.meta.env.VITE_TEST_SERVER_AUTH));
Checkstyle complaint

2025-04-01 06:54 UTC, Arnei approved these changes

2025-04-01 06:54 UTC, merged