Add discernible text to prev/next pagination buttons.
opencast/opencast-admin-interface pull request #553
Opened 2024-06-04 10:14 UTC by luniki

Fixes https://github.com/opencast/opencast-admin-interface/issues/529

2024-06-04 11:11 UTC, ziegenberg commented
Hi @luniki,

the build failed. Could you have a look and fix the errors.

2024-06-04 12:57 UTC, ziegenberg requested changes

2024-06-04 12:57 UTC, ziegenberg commented on src/components/shared/Table.tsx
> +						<span className="sr-only">{t("EVENTS.EVENTS.TABLE.PREVIOUS")}</span>
I couldn't find where the lang string `EVENTS.EVENTS.TABLE.PREVIOUS` is in use anywhere else.

As `EVENTS.EVENTS.TABLE.*` is specific to the events table, and as `src/components/shared/Table.tsx` is shared between all tables, I suggest moving the `PREVIOUS` and `NEXT` lang string to the top level, maybe next to `TABLE_NO_RESULT` or `TABLE_LOADING`.

Could you make the neccessaray changes in `src/i18n/org/opencastproject/adminui/languages/lang-en_US.json`?

2024-06-05 03:47 UTC, luniki commented on src/components/shared/Table.tsx
> +						<span className="sr-only">{t("EVENTS.EVENTS.TABLE.PREVIOUS")}</span>
Ok, sure.

2024-06-05 07:32 UTC, ziegenberg approved these changes

2024-06-05 07:33 UTC, merged