Sort specific lists in dropdown menu alphabetically
opencast/opencast-admin-interface pull request #575
Opened 2024-06-04 14:09 UTC by owi92

This adds a function to check whether the options for a dropdown menu are custom ordered. If they are not, the resulting list is ordered alphabetically. Otherwise the ordering is left as is (this would be the case for the "license" field for example).

Closes #567

2024-06-04 14:46 UTC, snoesberger commented
I can confirm that the sorting is working. I tested it for the event language and series drop down field in the modify pop-up. The licence field isn't sorted, because this is handled by the opencast config (see comment https://github.com/opencast/opencast-admin-interface/issues/567#issuecomment-2147413835)

2024-06-04 14:50 UTC, lkiesow requested changes

2024-06-04 14:50 UTC, lkiesow commented on src/utils/dropDownUtils.ts
> +
If I understand this correctly, this will only indicate if any of the items has a field `order`.

2024-06-04 14:50 UTC, lkiesow commented on src/utils/dropDownUtils.ts
> +		? formattedOptions
If any item has a field order, this will not use the order field for sorting, but stop sorting this at all. Or am I mistaken.

2024-06-04 15:16 UTC, owi92 commented on src/utils/dropDownUtils.ts
> +
Yes, that is correct. I suppose this could check instead if all items have that field - or are you saying that checking for that simply isn't enough to imply custom ordering? If that is the case, I'm honestly not sure how else to do it.

2024-06-04 15:17 UTC, owi92 commented on src/utils/dropDownUtils.ts
> +		? formattedOptions
Right, good point. I didn't touch this because I somehow thought they would already be ordered as configured, but now that you mention it I checked, and that does not seem to be the case.

2024-06-07 11:47 UTC, lkiesow approved these changes

2024-06-07 11:47 UTC, merged