Show build information
opencast/opencast-admin-interface pull request #584
Opened 2024-06-04 17:57 UTC by lkiesow

This patch adds additional build information like the build date to the footer and also adds the explanation we had on the old interface what these values mean to the `title` attributes.

This fixes #332

2024-06-04 20:12 UTC, gregorydlogan requested changes

2024-06-04 20:12 UTC, gregorydlogan commented on src/components/Footer.tsx
> +	const lastModified = user?.ocVersion?.['last-modified']
I'm guessing this is not quite right?

```
greg@fw13:~/opencast/opencast-admin-interface$ rm -rf build/
export PUBLIC_URL=/admin-ui
npm run build

> admin-ui-picard@0.1.0 build
> tsc && vite build

src/slices/userInfoSlice.ts:154:5 - error TS2322: Type 'string' is not assignable to type 'number'.

154     ocVersion.lastModified = new Date(ocVersion['last-modified']).toISOString().substring(0, 10);
        ~~~~~~~~~~~~~~~~~~~~~~

src/slices/userInfoSlice.ts:154:49 - error TS2551: Property 'last-modified' does not exist on type 'OcVersion'. Did you mean 'lastModified'?

154     ocVersion.lastModified = new Date(ocVersion['last-modified']).toISOString().substring(0, 10);
                                                    ~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/slices/userInfoSlice.ts:154
```

2024-06-05 08:57 UTC, lkiesow commented on src/components/Footer.tsx
> +	const lastModified = user?.ocVersion?.['last-modified']
I think you tested an old version of this. I've updated the patch before you commented on this

2024-06-05 18:57 UTC, ziegenberg commented
Does this show the Opencast Information (https://github.com/opencast/opencast) or the Admin UI Information (https://github.com/opencast/opencast-admin-interface)? Because, as they now come from different GIT repos it could be a different combination than the official release.

2024-06-05 18:58 UTC, ziegenberg commented
And should we probably have both pieces of information down there?

2024-06-06 10:15 UTC, lkiesow commented
I think the help texts are actually pretty clear on that:

```json
"DATE_DESC":"Date this system's kernel module was built on.",
"COMMIT": "Git commit this version of Opencast was built from.",
"VERSION": "Common bundle version of Opencast modules"
```

It's all Opencast like it was before. Not the admin interface. Knowing the Opencast version, you also know the admin interface version btw. Also, showing both versions publically is probably confusing to users.

That being said, we may want to include them as metadata like we did in the Editor:
```html
<meta name="git-commit" content="9b3752b1b8e46411cb5ff17c4b3751f97d193d9f">
<meta name="build-date" content="2024-06-01T20:30:33.816Z">
```
But that's aanother issue.

2024-06-10 14:19 UTC, lkiesow commented
@ziegenberg, do you think this is okay like it is?

2024-06-10 14:53 UTC, ziegenberg commented
Sure, that sounds good to me! 👍🏻

2024-06-11 04:01 UTC, merged