Fix wizard stepper that drifts out of window
opencast/opencast-admin-interface pull request #644
Opened 2024-06-05 13:16 UTC by marwyg

Fixes the wizard steps that are going out of the window in #612.

The text of the wizard steps include word breaking in non blank spaces now. I don't know if this is a good solution, what do you think.

2024-06-05 13:19 UTC, marwyg commented
This is how it looks with the change:

![grafik](https://github.com/opencast/opencast-admin-interface/assets/5593139/720bfde5-c014-401a-9ee1-e9975b6e866b)

and here with even one more step:

![grafik](https://github.com/opencast/opencast-admin-interface/assets/5593139/4759afe9-2fe2-4640-8077-0ff5a673039e)

2024-06-05 13:35 UTC, Arnei requested changes
At some point we will have to accept that we only have two lines for our text:

![Bildschirmfoto vom 2024-06-05 15-33-19](https://github.com/opencast/opencast-admin-interface/assets/14070005/30061fc1-9074-40dc-b40c-4a53115a358c)

2024-06-05 13:35 UTC, Arnei commented on src/styles/components/_steps.scss
> +        flex: 1 1 min-content;
What does this achieve?

2024-06-05 13:35 UTC, Arnei commented on src/styles/components/_steps.scss
> +        padding: 24px 0;
What does this achieve?

2024-06-05 14:29 UTC, kruemelm0nsta commented
maybe we could work on the wordbreaking? (minor priority)

2024-06-06 07:39 UTC, marwyg commented on src/styles/components/_steps.scss
> +        flex: 1 1 min-content;
Which line do you mean? Or do you mean all of them?
- So word-break makes, that words with no blanks starting to wrap like 'Zusammenfassung'
- The padding removes the spacing between the text to the edges, so the text has more room. In combination with the removal of the padding in MuiStepButton there is no padding left and the spacing is fully managed by the flexbox.
- The flex: 1 and 1 means that the elements shall grow and shrink equally. The min-content sets the initial width of the elements to the content of the smallest one.

I tested this again in Firefox and Chrome. I am no expert in CSS, so I am not 100% sure, but the removal of some of the lines will change things when you remove or add things in combination with the other changes I made or when there are more or less elements in the wizard.

2024-06-06 07:40 UTC, marwyg commented on src/styles/components/_steps.scss
> +        padding: 24px 0;
The padding is to remove the padding from the buttons like described in the above comment. It's to remove all padding left and right of the wizard elements to give the text more space.

2024-06-06 07:48 UTC, marwyg commented
So I tested the CSS changes again after Arnes comments and maybe it would be better to just remove the wordbreaking? I added one extra wizard step with a long text and it still works without wordbreaking:

![grafik](https://github.com/opencast/opencast-admin-interface/assets/5593139/4084eb06-1845-4fc6-9d17-e468b3b8768f)

So there is room for one additional step currently and if in the future someone should add more steps, maybe this person can deal with the styling then? I tried to test some languages, but when clicking on the above link, there seem only 3 languages work? German, English, Dutch?

2024-06-06 07:51 UTC, kruemelm0nsta commented
for the translation issue @ziegenberg is on it

2024-06-06 13:52 UTC, Arnei commented on src/styles/components/_steps.scss
> +        padding: 24px 0;
I see it now, thanks for the explanation.

2024-06-06 14:00 UTC, Arnei commented
> So I tested the CSS changes again after Arnes comments and maybe it would be better to just remove the wordbreaking? I added one extra wizard step with a long text and it still works without wordbreaking:
> 
> ![grafik](https://private-user-images.githubusercontent.com/5593139/337169175-4084eb06-1845-4fc6-9d17-e468b3b8768f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc2ODIyNzgsIm5iZiI6MTcxNzY4MTk3OCwicGF0aCI6Ii81NTkzMTM5LzMzNzE2OTE3NS00MDg0ZWIwNi0xODQ1LTRmYzYtOWQxNy1lNDY4YjNiODc2OGYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDZUMTM1MjU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGMyNzYzOGMzOGVkNDYzMmEzOGI2YjQzYzA2OGE3YjQ2NzczNGFjYWNkZTcwYzEyM2U5OWQwMDYyNWQ1ODAxMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.EbYsjDleNzfFxg6jnWmmkqHjsbhGu0ocghpo6GHHB9c)
> 

Not fond of this personally, as we have to sacrifice the even spacing between the buttons for it. But I'll gladly let people outvote me on that.

2024-06-14 07:53 UTC, marwyg commented on src/styles/components/_steps.scss
> +        flex: 1 1 min-content;
There are other flex configurations that I am overwriting.

https://github.com/opencast/opencast-admin-interface/assets/5593139/5d4ae7f9-ceca-4ba2-9401-64064fe46954

2024-06-14 07:57 UTC, marwyg commented
Even spacing sounds good, too :) We also can leave it as it is. That's fine by me.

2024-07-11 07:58 UTC, Arnei commented on src/styles/components/_steps.scss
> +        flex: 1 1 min-content;
My bad, you are of course correct. Thank you for taking the time to make a video.

2024-07-17 11:58 UTC, ziegenberg commented
Translation issue should be fixed by now.

2025-03-31 11:37 UTC, JulianKniephoff approved these changes

2025-03-31 11:38 UTC, JulianKniephoff commented
Should we have issues tracking the open discussion points or are people satisfied with this?

2025-04-01 08:35 UTC, Arnei commented
Might have to ping the people you want to answer that directly, I think the only one with major critique was me ^^'.

2025-04-01 09:28 UTC, JulianKniephoff commented
Fair 😛

2025-04-02 06:51 UTC, merged