Fix type error for missing organization property
opencast/opencast-admin-interface pull request #715
Opened 2024-06-19 15:47 UTC by lkiesow

If an organization property does not exist, the admin interface completely breaks in some cases. This seems to happen on admin-interface.opencast.org right now:

```
Uncaught TypeError: u.toLowerCase is not a function
    qr Footer.tsx:25
    React 8
    D scheduler.production.min.js:13
    $ scheduler.production.min.js:14
Footer.tsx:25:80
```

What's interesting is that this only seems to happen with the compiled code. Starting the development server, calling `toLowerCase()` just works.

In any case, this patch fixes the issue by providing the default value first, so that `toLowerCase()` is always called on a string.

2024-06-20 14:43 UTC, Arnei approved these changes

2024-06-24 09:54 UTC, JulianKniephoff requested changes

2024-06-24 09:54 UTC, JulianKniephoff commented on src/components/Footer.tsx
> +	const aboutEnabled = (orgProperties['org.opencastproject.admin.display_about'] || 'false').toLowerCase() === 'true';
```suggestion
	const aboutEnabled = (orgProperties['org.opencastproject.admin.display_about'] ?? 'false').toLowerCase() === 'true';
```

2024-06-24 09:54 UTC, JulianKniephoff commented on src/components/events/partials/modals/SeriesDetails.tsx
> +	const themesEnabled = (orgProperties['admin.themes.enabled'] || 'true').toLowerCase() === 'true';
```suggestion
	const themesEnabled = (orgProperties['admin.themes.enabled'] ?? 'true').toLowerCase() === 'true';
```

2024-06-24 09:54 UTC, JulianKniephoff commented on src/components/events/partials/wizards/NewSeriesWizard.tsx
> +	const themesEnabled = (orgProperties['admin.themes.enabled'] || 'true').toLowerCase() === 'true';
```suggestion
	const themesEnabled = (orgProperties['admin.themes.enabled'] ?? 'true').toLowerCase() === 'true';
```

2024-06-24 09:54 UTC, JulianKniephoff commented on src/components/shared/MainNav.tsx
> +	const themesEnabled = (orgProperties['admin.themes.enabled'] || 'true').toLowerCase() === 'true';
```suggestion
	const statisticsEnabled = (orgProperties['admin.statistics.enabled'] ?? 'false').toLowerCase() === 'true';
	const themesEnabled = (orgProperties['admin.themes.enabled'] ?? 'true').toLowerCase() === 'true';
```

2024-06-24 14:49 UTC, lkiesow commented on src/components/Footer.tsx
> +	const aboutEnabled = (orgProperties['org.opencastproject.admin.display_about'] || 'false').toLowerCase() === 'true';
This would only have an effect if the default value is `true`. Since the default value here is `false` this should behave identical, shouldn't it?

I mean, the difference is essentially just what happens if the key exists but is empty:

```ts
('' || 'false) => 'false'
('' ?? 'false') => ''

('false' === 'true') => false
('' === 'true') => false
```

If the default value is `'true'`, the effect would differ and the empty string would be considered a valid value equal to `false`.  The old code and old behavior in the case `…` was set to an empty string was:

https://github.com/opencast/opencast-admin-interface/blob/e6cb18f8f4efc0054474ba5cab20898ee2180642/src/components/events/partials/modals/SeriesDetails.tsx#L65

This means that the empty string was treated as no value. Your code would change that behavior. This could cause confusion since an existing configuration may change in meaning. Technically, that shouldn't happen within a minor version of Opencast. If we change that, we should also make sure that's happening consistently in all the code.

Long story short: If there is no good reason to change the behavior, so far you didn't provide any reasoning for the change, I suggest leaving it as is.

2024-06-24 15:07 UTC, JulianKniephoff commented on src/components/Footer.tsx
> +	const aboutEnabled = (orgProperties['org.opencastproject.admin.display_about'] || 'false').toLowerCase() === 'true';
That's fair, I was a bit quick with these suggestions.

For the record: I don't like using `||` for this purpose, and I also think it's weird that an empty string is handled differently from `" "` for example. (Or from `"foobar"` for that matter ...). But I guess that's outside the scope of this PR. 🤷‍♀️

2024-06-24 15:07 UTC, JulianKniephoff reviewed
Chaning my review to a "comment;" see https://github.com/opencast/opencast-admin-interface/pull/715#discussion_r1651199936

2024-06-26 06:53 UTC, merged