Allow admins to save ACLs with no write roles
opencast/opencast-admin-interface pull request #719
Opened 2024-06-20 11:47 UTC by dennis531

Closes #717

2024-06-20 15:37 UTC, Arnei requested changes

2024-06-20 15:37 UTC, Arnei commented on src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
> +			if (policy.read && policy.write || user.isAdmin) {
While this probably also works, I suggest using `hasAccess = (role: string, userInfo: UserInfoState)` in `utils/utils.ts` instead, for consistency.

2024-06-20 15:37 UTC, Arnei commented on src/slices/aclSlice.ts
> +		if (acls[i].read && acls[i].write || user.isAdmin) {
Same as above

2024-06-20 16:55 UTC, lkiesow commented on src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
> +			if (policy.read && policy.write || user.isAdmin) {
How would you use `hasAccess(…)` here? I don't see how this could be used in a sensible way. Sure, something like this would work:
```ts
if (policy.read && policy.write || hasAccess('', user)) {
```
But that's also just a `user.isAdmin` internally with additional confusing parameters?

2024-06-21 06:52 UTC, Arnei commented on src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
> +			if (policy.read && policy.write || user.isAdmin) {
From what I've seen in the code, checking for admin rights is never done by directly accessing the `isAdmin` property, but always by calling `hasAccess([...])` like so:
```
hasAccess("ROLE_ADMIN", user)
```
Is that because the information in the `isAdmin` property is unreliable? Maybe, I don't actually know. I'm mainly proposing this in the interest of code consistency.

2024-06-21 13:21 UTC, lkiesow commented on src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
> +			if (policy.read && policy.write || user.isAdmin) {
The method `hasAccess(…)` itself uses `isAdmin`:
```ts
src/utils/utils.ts:123:  return !!(userInfo.isAdmin || userInfo.roles.includes(role));
```
and `isAdmin` does exactly the same role check:
```ts
src/slices/userInfoSlice.ts:120:  state.isAdmin = userInfo.roles.includes("ROLE_ADMIN");
```

This means that `hasAccess("ROLE_ADMIN", user)` is essentially

```ts
userInfo.roles.includes("ROLE_ADMIN") || userInfo.roles.includes("ROLE_ADMIN")
```

That works, but doesn't make that much sense. If we have the simple check for an admin and that is exactly what we want, I find it pretty unintuitive to intentionally complicate this by using another wrapper around that.

2024-07-02 16:17 UTC, merged