Custom roles in ACL policy
opencast/opencast-admin-interface pull request #729
Opened 2024-06-21 11:03 UTC by dennis531

# Changes
- Add create option function to dropdown component
- Add button "new custom role" to create a policy with a new custom role

# Alternative 
We could show only one button "new policy" and enable the creation in the dropdown

# Screenshot
![grafik](https://github.com/opencast/opencast-admin-interface/assets/44410838/9d8b1f08-b44c-4b60-9c3f-681e6090804f)

2024-06-24 10:05 UTC, Arnei approved these changes
Code works and looks reasonable.

2024-06-24 11:23 UTC, dennis531 commented
I prefer to have only one button, as the new create dropdown can also be used to select existing ACLs. In my opinion, this separation would rather confuse users and lead to lower usability. 

We could also use the create dropdown for editing roles to avoid the workaround of removing policies.

2024-07-08 10:18 UTC, dennis531 commented
> I prefer to have only one button, as the new create dropdown can also be used to select existing ACLs. In my opinion, this separation would rather confuse users and lead to lower usability.
> 
> We could also use the create dropdown for editing roles to avoid the workaround of removing policies.

Done as described.

2024-07-11 08:20 UTC, Arnei requested changes
Works and looks good to me. Really like this over having an extra button. One minor nitpick below.

2024-07-11 08:20 UTC, Arnei commented on src/components/shared/DropDown.tsx
> +					noOptionsMessage={() => "No matching results."}
Should be a translatable

2024-07-11 12:29 UTC, dennis531 commented on src/components/shared/DropDown.tsx
> +					noOptionsMessage={() => "No matching results."}
I added the property to the false component. It should be correct now.

2024-07-11 12:50 UTC, Arnei approved these changes

2024-07-12 10:15 UTC, merged