Add support for various config options in listprovider/acl.default.create.properties
opencast/opencast-admin-interface pull request #741
Opened 2024-06-25 15:27 UTC by Arnei

This should add support for
- read_enabled 
- write_enabled 
- read_readonly 
- write_readonly 
- default_actions
- keep_on_template_switch_role_prefixes

To review, check `listprovider/acl.default.create.properties` in your Opencast , read what the options are all about and fiddle around with them.

There are two more config options in the listprovider that this does not add support for. Those two options were required for https://github.com/opencast/opencast/pull/4487, but are essentially code duplication and as such I would like to avoid using them.

Helps with #409.

2024-11-13 16:01 UTC, snoesberger commented
Thanks for this fix! I have tested this PR and the settings in `listprovider/acl.default.create.properties` are now respected if I add a new role in the acl view.

2025-01-30 13:54 UTC, owi92 requested changes
I tested the available options and apart from the `read_readonly` default, everything is working.

2025-01-30 13:54 UTC, owi92 commented on src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
> +																											&& aclDefaults["read_readonly"] === "true")
The default for this is
```
# The read property of the displayed access policy cannot be changed
# Default: true
# read_readonly = true
```

So I think you need to change this to
```suggestion
(aclDefaults && aclDefaults["read_readonly"] !== "false")
```

2025-01-31 10:13 UTC, Arnei commented on src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
> +			}
You approach assumes that every string that is not "true" should evaluate to false. I'd rather not do that, as false is not the default value for every option and I want to avoid admins accidentally setting an option to false that they did not intend to. (Would be even better if we could alert admins in case they made a typo, but not sure how to achieve that).

2025-01-31 10:17 UTC, owi92 commented on src/components/shared/modals/ResourceDetailsAccessPolicyTab.tsx
> +			}
Ok sure, then keep it as is 👍

2025-01-31 10:30 UTC, owi92 approved these changes
All good once you fix the missing closing parenthesis from my suggestion.

2025-02-04 14:51 UTC, merged