Fix checkstyle issues and siable sourcemaps
opencast/opencast-admin-interface pull request #743
Opened 2024-06-26 07:43 UTC by Arnei

ESLint is back, yay. But while it was gone, other PRs introduced checkstyle issues, oh no. This fixes those issues.

Secondly, this also disables sourcemaps. I was unable to build the project due to out-of-memory errors, and disabling sourcemaps proved a workaround. We can probably enable them again once we get rid of all the old dependencies that come with our current ESLint config.

2024-06-26 08:34 UTC, lkiesow commented
Not having source maps is really annoying. II'm not a fan of disabling them

2024-06-26 08:42 UTC, lkiesow commented
Where did you see the errors? I may just be that my machine has more RAM, but this just worked fine for me:

```diff
❯ git diff     
diff --git a/vite.config.ts b/vite.config.ts
index cfb30b8b8b..7238421677 100644
--- a/vite.config.ts
+++ b/vite.config.ts
@@ -9,7 +9,7 @@ export default defineConfig({
     plugins: [react(), svgr(), viteTsconfigPaths(), preserveDirectives()],
     build: {
         outDir: "build",
-        sourcemap: false,
+        sourcemap: true,
     },
     server: {
         open: true,

opencast-admin-interface (c81ceb4) [!?] via  v20.12.2 
❯ npm run build

```

2024-06-26 08:48 UTC, Arnei commented
What happened when building was

```
=============
vite v5.2.12 building for production...
✓ 2344 modules transformed.
rendering chunks (1)...
<--- Last few GCs --->

[14902:0x6a73ab0]    22156 ms: Mark-Compact (reduce) 2026.4 (2082.0) -> 2026.2 (2083.0) MB, 994.04 / 0.00 ms  (average mu = 0.176, current mu = 0.010) allocation failure; scavenge might not succeed


<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xb82c28 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]
 2: 0xeed540 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 3: 0xeed827 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char const*, v8::OOMDetails const&) [node]
 4: 0x10ff3c5  [node]
 5: 0x1117248 v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags) [node]
 6: 0x10ed361 v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 7: 0x10ee4f5 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment) [node]
 8: 0x10cbb46 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlignment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 9: 0x1527976 v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8::internal::Isolate*) [node]
10: 0x7f9b8f699ef6 
Abgebrochen (Speicherabzug geschrieben)
```

but now I can't reproduce it anymore. Maybe a hiccup in my system?

2024-06-26 09:16 UTC, JulianKniephoff commented
Maybe this is due to #709? 🤔

2024-06-26 09:22 UTC, JulianKniephoff requested changes
Seems to be known: https://github.com/vitejs/vite/issues/2433

I would also argue against removing source maps. Can we increase the heap memory of the node process in CI like the upstream issue suggests? 🤔

2024-06-26 13:04 UTC, lkiesow commented
If we maybe can mitigate this with env exports if necessary, do we want to merge it like this and add the env exports to  the `package.json` and/or the CI scripts if necessary?

2024-06-26 13:07 UTC, JulianKniephoff approved these changes
Apart from disabling sourcemaps this just seems to fix lints, so yeah, let's get this in and take care of the memory issue in its own PR.

2024-06-26 13:21 UTC, merged

2024-06-27 10:51 UTC, lkiesow commented
Looking at the CI workflows, we don't seem to run in memory issues there:
https://github.com/opencast/opencast-admin-interface/actions/workflows/test.yml