Add a very restricted form of `no-tabs` to the ESLint config
opencast/opencast-admin-interface pull request #749
Opened 2024-06-26 15:47 UTC by JulianKniephoff

This is in preparation to adopting `@opencast/eslint-config-ts-react`,
which includes `no-tabs`.

We use tabs for indentation in some places, but also for other things.
The indentation tabs are easy to get rid of automatically, if a bit annoying.
It is the **other** instances that are not so easily picked out,
and especially distinguished from valid tab usages (think literals).

So I'm getting these out of the way first.

2024-06-28 08:45 UTC, Arnei requested changes
Looks reasonable and builds. Got one question:

2024-06-28 08:45 UTC, Arnei commented on src/components/shared/TableFilterProfiles.tsx
> +                        className="button-li ke-anchor"
Should there even be a whitespace breaking up the class name here?

2024-07-08 13:08 UTC, JulianKniephoff commented on src/components/shared/TableFilterProfiles.tsx
> +                        className="button-li ke-anchor"
Probably. 👀

2024-07-08 15:04 UTC, Arnei approved these changes

2024-07-23 21:48 UTC, merged