Asset-Upload fixed
opencast/opencast-admin-interface pull request #750
Opened 2024-06-26 19:39 UTC by wsmirnow

This patch fixes the asset upload.

2024-06-28 08:18 UTC, Arnei requested changes
Works and makes sense to me.

Ideally we would not have to make assumptions about magic variables in workflows and have the backend sort it out somehow, but arguably restoring the upload to working order is more important and the assumptions we have to make are not too annoying.

Minor nitpicks below:

2024-06-28 08:18 UTC, Arnei commented on src/i18n/org/opencastproject/adminui/languages/lang-en_US.json
> +		"EVENTS_UPDATED": "The event have been successfully updated",
```suggestion
		"EVENTS_UPDATED": "The event has been successfully updated",
```

2024-06-28 08:18 UTC, Arnei commented on src/slices/eventDetailsSlice.ts
> +        configuration: typeof uploadAssetWorkflowConfiguration,
Should be using tabs instead of spaces for indentation.

2024-06-28 08:18 UTC, Arnei commented on src/slices/eventDetailsSlice.ts
> +	let uploadAssetWorkflowConfiguration: {
Minor stylistic nitpick: It is preferred to use `const` instead of `let` whenever possible.

2024-06-28 08:20 UTC, Arnei commented on src/slices/eventDetailsSlice.ts
> +	let assetFlavors: string = "";
It is not necessary to type everything explicitly. For example, in this case typescripts type inference would have no problem inferring that this should be a string.

2024-07-08 14:12 UTC, wsmirnow commented on src/slices/eventDetailsSlice.ts
> +        configuration: typeof uploadAssetWorkflowConfiguration,
done

2024-07-08 14:13 UTC, wsmirnow commented on src/slices/eventDetailsSlice.ts
> +	let uploadAssetWorkflowConfiguration: {
Thank you for the info. I've updated the PR.

2024-07-08 14:14 UTC, wsmirnow commented
Thank you @Arnei. I've updated the PR with your suggestions. Please continue review.

2024-07-09 06:54 UTC, Arnei approved these changes

2024-07-10 14:00 UTC, merged