Fixes video preview displaying wrong video
opencast/opencast-admin-interface pull request #814
Opened 2024-07-04 10:43 UTC by Arnei

The video preview player in the event assets details would try to display the media from the assets previously visited, which would lead to the player displaying no or the wrong video. This fixes that by ensuring that the player reloads when the url changes.

Fixes #466.

2024-07-09 20:42 UTC, lkiesow requested changes
Looks good in general. I'm not sure if the mime type is needed. Testing this locally, videos do not work for me in either Firefox or Chromium. But that may also be caused by them being loaded from develop directly?

2024-07-09 20:42 UTC, lkiesow commented on src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
> +										<video ref={videoRef} id="player" controls>
This also displays for subtitle or audio tracks. Maybe we can do something like:
- if `media.has_video` → `<video …`
- else if `media.has_audio` → `<audio …`
- else hide this section

2024-07-10 07:02 UTC, Arnei commented on src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
> -											<source src={media.url} type="video/mp4" />
Good catch, thanks.

2024-07-10 07:03 UTC, Arnei commented on src/components/events/partials/ModalTabsAndPages/EventDetailsAssetMediaDetails.tsx
> +										<video ref={videoRef} id="player" controls>
Reasonable, but I would leave that for a different PR. This is just about loading the correct media file at all.

2024-07-16 17:02 UTC, merged