Show workflow operations when clicking on status in events table
opencast/opencast-admin-interface pull request #817
Opened 2024-07-08 07:38 UTC by dennis531

Open the workflow operations of the last workflow.

Changes:
- Move navigation logic of event details modal to the redux store to allow modals to be opened from different locations.
- When clicking on status in the events table, open the operations of the last workflow. If no workflow exists in the event, show the workflow overview.

2024-07-08 20:48 UTC, lkiesow requested changes
I really like this :heart: 
But there are a few minor issues:
- The tooltip still says it will filter events
- I've tested this with running, finished and failed events and it works fine. Clicking on scheduled events does nothing though. Maybe we could open the event details scheduling tab for those?
- I haven't tested with events in state recording. I would probably treat them similar to scheduled events and open the scheduling tab.

2024-07-09 07:49 UTC, Arnei commented on src/components/events/partials/EventsStatusCell.tsx
> +				dispatch(openModal(EventDetailsPage.Workflow, row, 'workflow-operations'));
Code generally looks reasonable and makes sense to me.

It would be great if we did could move this code (or part of it) into the related event details component somehow, so we can avoid having to know how the event details components works in this unrelated component. Phrased differently, the EventStatusCell should not need to know which GET requests to send in order to populate the workflow details. But I understand if that this might be difficult, so no biggie if it's not possible.

2024-07-09 08:31 UTC, dennis531 commented on src/components/events/partials/EventsStatusCell.tsx
> +				dispatch(openModal(EventDetailsPage.Workflow, row, 'workflow-operations'));
I also don't like the fetches at this place. I had tried to remove them, but I found out that nested tabs load the content independently of each other. As a result, the data was not loaded when navigating to the previous navigation item. 

I'll look at it again and try to find a better solution.

2024-07-09 09:01 UTC, dennis531 commented
> * I've tested this with running, finished and failed events and it works fine. Clicking on scheduled events does nothing though. Maybe we could open the event details scheduling tab for those?
> 
> * I haven't tested with events in state recording. I would probably treat them similar to scheduled events and open the scheduling tab.

There was a bug. In these cases, the workflow overview should be opened. I think the schedule tab would be more useful because these events have no workflows.

2024-07-09 12:56 UTC, dennis531 commented on src/components/events/partials/EventsStatusCell.tsx
> +				dispatch(openModal(EventDetailsPage.Workflow, row, 'workflow-operations'));
I hope the current solution looks better. Now the data is fetched in the modal components again. The main problem is that we need to pass which data (e.g. workflow, error etc.) should be shown in the modal. The implemented function only allows to select an event and a workflow. It still feels a bit hacky.

2024-07-10 08:13 UTC, Arnei commented on src/components/events/partials/EventsStatusCell.tsx
> +				dispatch(openModal(EventDetailsPage.Workflow, row, 'workflow-operations'));
Arguably that is fine? If we want to open a specific workflow tab in the event details from anywhere, and have the, workflow tab load stuff by itself, we will have to pass the workflowId somehow.

2024-07-10 08:15 UTC, Arnei requested changes

2024-07-10 08:15 UTC, Arnei commented on src/components/events/partials/modals/EventDetails.tsx
> +	const workflowId = useAppSelector(state => getModalWorkflowId(state))!;
If we're only fetching the workflowId here to pass it on, the components could just fetch it themselves, no?

2024-07-10 11:37 UTC, dennis531 commented on src/components/events/partials/modals/EventDetails.tsx
> +	const workflowId = useAppSelector(state => getModalWorkflowId(state))!;
Yes, I will change it.

2024-07-11 06:29 UTC, Arnei approved these changes

2024-07-16 16:58 UTC, lkiesow requested changes
I just realized that the tooltips are still incorrect:

![Screenshot from 2024-07-16 18-56-29](https://github.com/user-attachments/assets/621d384b-c170-406b-964f-041581d4062a)

This does no longer add a filter

2024-07-17 11:41 UTC, dennis531 commented
> I just realized that the tooltips are still incorrect:

I think your language is set to `en-GB`?

I only changed the language for `en-US`. How should we handle the translations in this case?

2024-07-18 21:22 UTC, lkiesow commented
upps, my bad. I had indeed selected `en-GB`

2024-07-18 21:22 UTC, merged