Feature request: terms of use for new user
opencast/opencast-admin-interface pull request #825
Opened 2024-07-09 12:48 UTC by schuettloeffel-elsa

closes #296

2024-07-09 13:41 UTC, schuettloeffel-elsa commented
Backend PR: https://github.com/opencast/opencast/pull/6010

2024-07-09 16:27 UTC, mtneug commented
@schuettloeffel-elsa, thanks for this PR. Linking terms of use makes sense. However, I'm wondering, since we now have a couple of links in the footer, if it would be better to have a generic way of putting links there. Something like a configuration map containing the link name and URL. Opinions?

2024-07-10 06:42 UTC, schuettloeffel-elsa commented
> Linking terms of use makes sense. However, I'm wondering, since we now have a couple of links in the footer, if it would be better to have a generic way of putting links there. Something like a configuration map containing the link name and URL. Opinions?

I dont really get what you mean, this PR doesnt provide any links in the footer, it just displays the terms if a user hasnt already accepted them. Or am I missing something here?

2024-07-10 07:23 UTC, mtneug commented
> I dont really get what you mean, this PR doesnt provide any links in the footer, it just displays the terms if a user hasnt already accepted them. Or am I missing something here?

Oh, my bad! I somehow assumed that this would add a "Terms of Use" link in the footer of the Admin UI similar to #306.

2024-07-10 07:54 UTC, schuettloeffel-elsa commented
No worries :)

2024-07-11 10:10 UTC, lkiesow requested changes
I didn't do a full review. This is more just a few comments.

2024-07-11 10:10 UTC, lkiesow commented on src/components/shared/TermsOfUseModal.tsx
> +		await axios.post("/admin-ng/user-settings/setting", body, {
Right now, I don't think this will work for any but admin users. The `/admin-ng/user-settings` isn't really used by anything right now. I'm also not sure if this works with non-persistent users at all. That definitely needs testing.

2024-07-11 10:10 UTC, lkiesow commented on src/components/shared/TermsOfUseModal.tsx
> +		axios.get(getURL(i18n.language))
More out of curiosity, why include axios as an external library and not just use The Fetch API?

2024-07-11 10:10 UTC, lkiesow commented on src/components/shared/TermsOfUseModal.tsx
> +									<div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(termsContent) }} ></div>
Would it make sense to expect and render something like Markdown instead of giving users the freedom to use HTML but then modify it anyway to avoid possible threads?

2024-07-11 12:56 UTC, lkiesow commented
One more request I forgot and which also applies to https://github.com/opencast/opencast/pull/6010

- It would be great if you could give your pull request a description of what the problem is, what you tried to achieve and if there is anything special about the way you fixed the problem. Even if you linked an issue, it's somewhat cumbersome for reviewers to always try to get information from somewhere else. Also, things can change, and you may get additional insights during the implementation. Definitely not the end of the world, but you will make reviewers happy.
- The pull requests titles will become part of the changelog. So it's great if the title describes what's happening. And this is no longer a feature request ;-P

2024-07-12 06:52 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +			console.error("Fehler beim Abrufen der Daten:", error);
Do you mean the console.error? Not really, but I can translate it to english if that helps

2024-07-12 07:02 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +		await axios.post("/admin-ng/user-settings/setting", body, {
Hm good call, just testet with a non admin user and that doesnt work. API respond:

```
{
"servlet":"/",
"message":"HTTP method POST is not supported by this URL",
"url":"/admin-ng/user-settings/setting",
"status":"400"
}
```

I mean `/admin-ng/user-settings` is kind of a cool feature, maybe we should make that work in the backend for all users?

2024-07-12 07:03 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +		axios.get(getURL(i18n.language))
Dont know to be honest :D

2024-07-12 07:08 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +									<div dangerouslySetInnerHTML={{ __html: DOMPurify.sanitize(termsContent) }} ></div>
Well you can still use normal html tags that would make sense in that case, DOMPurify.sanitize doenst remove usual html tags used for styling etc. Makes sense so me since terms of use will need some styling to maintain a good readability

2024-07-12 07:12 UTC, schuettloeffel-elsa commented
> One more request I forgot and which also applies to [opencast/opencast#6010](https://github.com/opencast/opencast/pull/6010)
> 
> * It would be great if you could give your pull request a description of what the problem is, what you tried to achieve and if there is anything special about the way you fixed the problem. Even if you linked an issue, it's somewhat cumbersome for reviewers to always try to get information from somewhere else. Also, things can change, and you may get additional insights during the implementation. Definitely not the end of the world, but you will make reviewers happy.

Sure! From other projects I know the workflow to just link to the issue (like I die here) and always retrieve the informations there, just to prevent doubled informations in the issue and PR. But if it helps I will give some informations in the PR as well in the future :)

> * The pull requests titles will become part of the changelog. So it's great if the title describes what's happening. And this is no longer a feature request ;-P

Haha, will do, thanks for editing

2024-07-12 07:55 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +		await axios.post("/admin-ng/user-settings/setting", body, {
From the chat:

> As far as I know, this was never used. Maybe it's just a matter of allowing this in the security XML file.
https://github.com/opencast/opencast/blob/9b7e6e0b0e53ea76366386527058735dacef71fc/etc/security/mh_default_org.xml#L109

2024-07-15 10:13 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +		await axios.post("/admin-ng/user-settings/setting", body, {
OK @lkiesow works now for non admin users after adding the endpoint to the security xml:
https://github.com/opencast/opencast/pull/6010/commits/e145b33e2c7c3a458242e773b944bfed5593453d

2024-07-15 10:14 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +		await axios.post("/admin-ng/user-settings/setting", body, {
I will test if this also works for non-persistent users

2024-07-15 12:46 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +		await axios.post("/admin-ng/user-settings/setting", body, {
@lkiesow just testet with an sso user which also works, so should be fine

2024-08-13 13:50 UTC, JulianKniephoff requested changes
Apart from the inline comments:

* We should really try to not add any more `ts-expect-error` and `eslint-disable` comments.

It would be nice if you could include a screenshot, as well.

2024-08-13 13:50 UTC, JulianKniephoff commented on .gitignore
> +.vscode
I think developer/tool specific ignores belong in `.git/info/exclude` or your personal git-config.

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +	const [termsContent, setTermsContent] = useState<string>("");
```suggestion
	const [termsContent, setTermsContent] = useState("");
```

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +	const initialValues = {};
This really doesn't need to be in a variable, let alone one that is declared so far from its use.

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +									Submit
This should be translated.

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +					initialValues={initialValues}
Is this prop really necessary if all you pass is an empty object? 🤔

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +					onSubmit={(values) => handleSubmit(values)}
```suggestion
					onSubmit={handleSubmit}
```

Saves creating a new closure every rerender.

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +					)}
```suggestion
					</>)}
```

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +						<>
```suggestion
					{(formik) => (<>
```

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +						setTermsContent(t("TERMS.NOCONTENT").toString());
What's the `toString` for here? 🤔

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/Header.tsx
> +			{displayTerms && <TermsOfUseModal />}
I kind of wonder what happens when both, the adopter registration modal and the terms modal are to be shown, and whether or not we are okay with that outcome ... 🤔

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +			const isAgreed = response.data.results.some(result => result.key === "agreedToTerms" && result.value === "true");
I would make this

```suggestion
			const isAgreed = response.data.results.find(result => result.key === "agreedToTerms").value === "true";
```

🤷‍♀️

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +		const checkTerms = async () => {
The indentation is kind of off here, right? 🤔

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +		checkTerms();
Why even make this a function only to then call it immediately. Just lift the body of `checkTerms` into the `useEffect` body.

2024-08-13 13:50 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +		};
Could you make this a top level function? That way it is not recreated on every render.

2024-08-13 14:38 UTC, JulianKniephoff requested changes
Another small thing.

Also here is a screenshot: 
<img width="929" alt="image" src="https://github.com/user-attachments/assets/151bf47c-bc0d-4713-bfb7-06235c8ea0c0">

Note that it has a little extra white padding at the bottom that we should probably get rid of.

2024-08-13 14:38 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +			return `ui/config/admin-ui/terms.${language}.html`;
I think this needs to be

```suggestion
			return `/ui/config/admin-ui/terms.${language}.html`;
```

See also https://github.com/opencast/opencast-admin-interface/pull/879.

2024-08-13 14:41 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +				axios.get(getURL(typeof i18n.options.fallbackLng === 'string' ? i18n.options.fallbackLng : 'en-US'))
In #306 you defaulted to `en-GB`. Any reason for this inconsistency? 🤔

2024-08-16 08:17 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +		checkTerms();
The function needs to be async, see: https://devtrium.com/posts/async-functions-useeffect

2024-08-16 08:20 UTC, schuettloeffel-elsa commented on src/components/Header.tsx
> +			{displayTerms && <TermsOfUseModal />}
That should never happen, since you cant press any button (like the adopters registration) when the terms are displayed. Or is there some other way the registration is forced to the user besides of pressing the button?

2024-08-16 08:38 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +				axios.get(getURL(typeof i18n.options.fallbackLng === 'string' ? i18n.options.fallbackLng : 'en-US'))
Since `lang-en_US.json` seems to be the main language file i thought it would be better to default to `en-US` - in #306 i wasnt aware of that, so maybe better change it there to `en-US` too?

2024-08-16 08:57 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +	const [termsContent, setTermsContent] = useState<string>("");
fixed it

2024-08-16 08:57 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +									Submit
is translated now

2024-08-16 08:57 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +	const initialValues = {};
removed the var

2024-08-16 08:58 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +					initialValues={initialValues}
yes it is for some reason

2024-08-16 08:58 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +		};
done

2024-08-16 08:59 UTC, schuettloeffel-elsa commented
> Note that it has a little extra white padding at the bottom that we should probably get rid of.

Done.

2024-08-16 09:00 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +		const checkTerms = async () => {
fixed it

2024-08-16 09:06 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +						setTermsContent(t("TERMS.NOCONTENT").toString());
removed it

2024-08-16 09:06 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +					onSubmit={(values) => handleSubmit(values)}
thanks, changed it

2024-08-16 09:06 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +						<>
done

2024-08-16 09:06 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +					)}
done

2024-09-05 15:44 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +				axios.get(getURL(typeof i18n.options.fallbackLng === 'string' ? i18n.options.fallbackLng : 'en-US'))
That sounds reasonable to me. 🤔

2024-09-05 15:46 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +		checkTerms();
You can just make the `useEffect`-callback `async`, no?

2024-09-05 15:53 UTC, JulianKniephoff commented on src/components/Header.tsx
> +			{displayTerms && <TermsOfUseModal />}
Wait what button are you talking about? AFAIK no user interaction is necessary for the adopter registration prompt to pop up the first time you use the admin UI.

However, we discussed this in the technical meeting and came to the agreement that this is probably fine since that should only happen for actual system admins (`ROLE_ADMIN` and org-admins). Those on the other hand probably don't need to see the terms since they are the ones setting up the system!

So the suggestion was to just add a condition here to only show the terms to non-admins.

2024-09-05 16:06 UTC, JulianKniephoff commented on src/components/shared/TermsOfUseModal.tsx
> +		};
No I mean really top-level, as in module-level, outside of the component.

2024-09-27 06:47 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +		checkTerms();
No not possible, since useEffect expects a function, but an async function returns a promise

2024-09-27 06:50 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +		};
Got it

2024-09-27 06:57 UTC, schuettloeffel-elsa commented on src/components/Header.tsx
> +			{displayTerms && <TermsOfUseModal />}
Done

2024-10-18 20:02 UTC, gregorydlogan requested changes

2024-10-18 20:02 UTC, gregorydlogan commented on src/components/shared/TermsOfUseModal.tsx
> +				axios.get(getURL(typeof i18n.options.fallbackLng === 'string' ? i18n.options.fallbackLng : 'en-US'))
This isn't quite working right.  I can see it requesting my region's terms (which correctly 404), and I can see it calling `setTermsContent` with the correct en-US terms.  But the modal itself never pops up.

2024-10-21 08:07 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +				console.error("Fehler beim Abrufen der Daten:", error);
Whups, changed it

2024-10-21 08:08 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +				axios.get(getURL(typeof i18n.options.fallbackLng === 'string' ? i18n.options.fallbackLng : 'en-US'))
Works fine for me, what user are you trying this with? `ROLE_ADMIN` will never see this, also the property 'org.opencastproject.admin.display_terms' has to be true

2025-01-16 21:02 UTC, gregorydlogan requested changes

2025-01-16 21:02 UTC, gregorydlogan commented on src/components/shared/TermsOfUseModal.tsx
> +	return `/ui/config/admin-ui/terms.${language}.html`;
This is querying for `/ui/config/admin-ui/terms.${language}.html`, but the Imprint page is loking for `ui/config/admin-ui/${location.pathname.split("/").pop()}.${language}.html`, which renders as `ui/config/admin-ui/imprint.en-US.html`

These should be the url, right?  I've filed https://github.com/opencast/opencast/pull/6427 thinking that it was supposed to be at any rate.

2025-03-10 09:19 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +	return `/ui/config/admin-ui/terms.${language}.html`;
No, the terms have nothing to do with the imprint, this should all be allright as is, you can also read in the docs that the right files are `terms.${language}.html` - so https://github.com/opencast/opencast/pull/6427 is obsolet.

2025-03-21 22:14 UTC, gregorydlogan requested changes

2025-03-21 22:14 UTC, gregorydlogan commented on src/components/shared/TermsOfUseModal.tsx
> +	if (agreedToTerms) {
This part isn't working.  It's also helped identify https://github.com/opencast/opencast/issues/6565, which is nice, but the server *is* responding to the settings query to `http://localhost/admin-ng/user-settings/settings.json` from the `UserInfoSlice` with sane looking data:

```
{
    "total": 1,
    "offset": 0,
    "limit": 100,
    "results": [
        {
            "id": 701,
            "value": "on",
            "key": "agreedToTerms"
        }
    ]
}```

2025-03-26 14:45 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +	if (agreedToTerms) {
Hm.. when I testet it 100 years go it worked fine :D Note that my code checks for agreedToTerms === "true", but your data responds with agreedToTerms = "on" - maybe thats the problem?

2025-04-02 22:38 UTC, gregorydlogan commented on src/components/shared/TermsOfUseModal.tsx
> +	if (agreedToTerms) {
Yep.  Looking at the back end, it's just spitting back whatever you feed it - no modifications.  Which means `on` is coming from the front end, and is sounds suspiciously like the CSS value of a checkbox when it's checked.  Maybe a check/munging of the value needs to be done in the `handleSubmit` method.

2025-04-03 07:29 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +	if (agreedToTerms) {
Ok weird, all my browsers set this to true when checked.. nevertheless, i added an extra check as you suggested, should hopefully do the trick now

2025-04-03 07:31 UTC, schuettloeffel-elsa commented on src/components/shared/TermsOfUseModal.tsx
> +	if (agreedToTerms) {
`body.append("value", values.agreedToTerms ? "true" : "false");`

<-- should now submit either "true" or "false" in any case.

2025-06-26 20:38 UTC, gregorydlogan commented
The backend on this is *finally* progressing, so hopefully news on this soon.  Maybe even in time for 18.0?

2025-08-28 06:58 UTC, pselsa commented
> The backend on this is _finally_ progressing, so hopefully news on this soon. Maybe even in time for 18.0?

Okay, since the backend issue is now done, we can merge this one now? 😇

2025-09-09 16:54 UTC, gregorydlogan commented
@schuettloeffel-elsa Do you want this in `develop` (and thus OC 19), or 18?  The backend changes went into 18, so this *could* go there if you want it there.

2025-09-09 17:07 UTC, gregorydlogan requested changes
Code has moved underneath you, so there are a few errors after merging now:
```
/home/greg/opencast/opencast-admin-interface/src/components/Header.tsx
  55:38   warning  Strings must use doublequote  quotes
  55:84   warning  Strings must use doublequote  quotes
  55:111  warning  Strings must use doublequote  quotes

/home/greg/opencast/opencast-admin-interface/src/components/shared/TermsOfUseModal.tsx
    1:8   warning  'React' is defined but never used. Allowed unused vars must match /^_/u                 @typescript-eslint/no-unused-vars
   25:22  error    Unsafe call of a(n) `any` typed value                                                   @typescript-eslint/no-unsafe-call
   25:36  error    Unsafe member access .results on an `any` value                                         @typescript-eslint/no-unsafe-member-access
   25:66  error    Unsafe member access .key on an `any` value                                             @typescript-eslint/no-unsafe-member-access
   25:91  error    Unsafe member access .value on an `any` value                                           @typescript-eslint/no-unsafe-member-access
   40:21  error    Unsafe argument of type `any` assigned to a parameter of type `SetStateAction<string>`  @typescript-eslint/no-unsafe-argument
   42:11  warning  'error' is defined but never used. Allowed unused args must match /^_/u                 @typescript-eslint/no-unused-vars
   43:58  warning  Strings must use doublequote                                                            quotes
   43:96  warning  Strings must use doublequote                                                            quotes
   45:23  error    Unsafe argument of type `any` assigned to a parameter of type `SetStateAction<string>`  @typescript-eslint/no-unsafe-argument
   48:21  warning  Strings must use doublequote                                                            quotes
   57:30  warning  Unexpected parentheses around single function argument                                  arrow-parens
   58:7   error    'body' is never reassigned. Use 'const' instead                                         prefer-const
   60:31  error    Unsafe member access .agreedToTerms on an `any` value                                   @typescript-eslint/no-unsafe-member-access
  101:8   warning  Unexpected parentheses around single function argument                                  arrow-parens
  132:11  error    Unsafe assignment of an error typed value                                               @typescript-eslint/no-unsafe-assignment
```

2025-09-10 07:50 UTC, schuettloeffel-elsa commented
> Code has moved underneath you, so there are a few errors after merging now:

--> Done

> @schuettloeffel-elsa Do you want this in `develop` (and thus OC 19), or 18? The backend changes went into 18, so this _could_ go there if you want it there.

Please, lets get this finally over with and put it into 18, i dont want to fix anything anymore when code changes 6 month from now 😄

2025-09-10 15:58 UTC, gregorydlogan commented
Ok, then you need to rebase this against `r/18.x` and change the target branch.  Let me know if you can't change the branch - that might be a committers-only thing.

Attempting to merge this into `r/18.x` yields conflicts, but given the age of the original commits the rebase shouldn't be a big deal.  I tested this merged into `develop` and saw this when I tried either the privacy statement or the imprint.

<img width="1169" height="112" alt="image" src="https://github.com/user-attachments/assets/45490cb8-b3fa-439e-88c4-c60a777c5790" />

2025-09-11 06:53 UTC, pselsa commented
Okay never mind, rebasing got way too complicated since i merged the dev branch into this pr branch and now its just a big mess.. lets put it into dev and close this pr, i dont want to put any more effort into this tbh

2025-09-15 21:01 UTC, merged