Fix height of filters
opencast/opencast-admin-interface pull request #831
Opened 2024-07-12 08:03 UTC by dennis531

Basically adds flexbox to elements and removes some useless `<span>`.

Close #804

2024-07-12 16:19 UTC, lkiesow requested changes

2024-07-12 16:19 UTC, lkiesow commented on src/styles/main.scss
> +      display: flex;
I would also suggest adding a slight `gap` here:
```suggestion
      display: flex;
      gap: 4px;
```

2024-07-12 16:19 UTC, lkiesow commented on src/styles/main.scss
>      display: flex;
The filters now run into each other:
![Screenshot from 2024-07-12 18-08-32](https://github.com/user-attachments/assets/a0540500-bc95-4f93-9db4-f964778d2a89)


I think some `gap` would make this better:
```suggestion
    display: flex;
    gap: 4px;
```

2024-07-12 16:20 UTC, lkiesow commented on src/styles/main.scss
>      display: flex;
This is how the filters look with both `gap` applied:

![Screenshot from 2024-07-12 18-19-40](https://github.com/user-attachments/assets/5c3be4ec-7a63-419e-9c6f-f058118b596f)

2024-07-13 10:37 UTC, dennis531 commented
@lkiesow Thanks for these suggestions. It looks much better now.

2024-07-16 08:30 UTC, dennis531 commented
Close #803

2024-07-16 16:38 UTC, merged