Unify Scheduling pages
opencast/opencast-admin-interface pull request #911
Opened 2024-09-12 13:06 UTC by Arnei

Fixes #221 

Reduces duplicate code between the scheduling page for creating a new event and for editing events.
Functionality should be unchanged.

2024-11-08 13:22 UTC, snoesberger commented
I have done some tests with this PR and found some problems:
- When I open a scheduled event, the date field is empty.
- Even though I enabled input channels A and B for my Extron SMP during the event creation process, the channels are not enabled.
- This issue is also valid here (and should maybe be fixed directly with this PR?) https://github.com/opencast/opencast-admin-interface/issues/941

![grafik](https://github.com/user-attachments/assets/2853792b-c087-41e4-a5a0-68359d55aac1)

2024-11-11 11:47 UTC, Arnei commented
Thanks for testing!
- Did the problems you found also occur without this PR? (I think I've seen the start date field being empty on another branch before, but I'm not sure)
- This PR does not intend to change functionality. To fix #941, a seperate PR would be better. (Getting this merged should make fixing it easier though)

2025-01-16 21:13 UTC, gregorydlogan requested changes

2025-01-16 21:13 UTC, gregorydlogan commented on src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
Missing symbols:
```
> tsc && eslint . --max-warnings=0 && vite build

src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx:445:18 - error TS2304: Cannot find name 'currentLanguage'.

445          locale={currentLanguage?.dateLocale}
                     ~~~~~~~~~~~~~~~

src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx:475:20 - error TS2304: Cannot find name 'currentLanguage'.

475            locale={currentLanguage?.dateLocale}
                       ~~~~~~~~~~~~~~~


Found 2 errors in the same file, starting at: src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx:445
```

2025-01-17 12:57 UTC, Arnei commented on src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
Can't reproduce this. The missing symbols are not present in the NewSourcePage.tsx?

2025-01-20 18:31 UTC, gregorydlogan commented on src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
They're not in the diff, they're in the `origin/main`.  I'm guessing `main` drifted underneath this PR.

2025-01-21 22:46 UTC, merged