Fix test containers
opencast/opencast-admin-interface pull request #945
Opened 2024-10-10 12:51 UTC by lkiesow

This patch fixes the test containers, which were failing since `git` is now required for building/running the admin interface.

2024-10-11 08:38 UTC, marcusm7 commented
Tested the docker image with:
docker run --rm -it -p 127.0.0.1:3000:3000 ghcr.io/opencast/opencast-admin-interface:pr-945

The git dependency is found now, but it can't find the git repo, it seems.

```
fatal: not a git repository (or any of the parent directories): .git
failed to load config from /admin-interface/vite.config.ts
error when starting dev server:
Error: Command failed: git rev-parse HEAD
fatal: not a git repository (or any of the parent directories): .git

    at genericNodeError (node:internal/errors:984:15)
...
```

2024-10-17 21:22 UTC, lkiesow commented
Should be fixed now

2024-11-21 14:55 UTC, mtneug requested changes
I would have used env variables with default values, but this also works. There is one outstanding typo and I would suggest having some default non-empty string.

2024-11-21 14:55 UTC, mtneug commented on vite.config.ts
> +const commitHash = child.execSync("giat rev-parse HEAD || cat commit || :").toString().trim();
```suggestion
const commitHash = child.execSync("git rev-parse HEAD || cat commit || echo 'unknown'").toString().trim();
```

2024-11-29 17:00 UTC, JamesUoM commented
Though it works it's using the default:

```
/bin/sh: git: not found
cat: can't open 'commit': No such file or directory
```

2024-11-29 19:11 UTC, ziegenberg approved these changes

2024-11-29 19:19 UTC, merged