Preselect all capture agent inputs when scheduling new event
opencast/opencast-admin-interface pull request #979
Opened 2024-11-12 10:27 UTC by Arnei

Aims to fix #941.

When scheduling a new event, if the selected capture agent has any inputs, the inputs are all preselected per default now. At least one input must remain selected. Input name should be rendered nicer now.

Note that these changes are only for when scheduling a new event (except the input name rendering), because the linked issue only talked about scheduling new events. For now I would leave the discussion on how this should work for existing events to a separate issue/pr.  

Quick showcase:
[Bildschirmaufzeichnung vom 2024-11-12 11-05-41.webm](https://github.com/user-attachments/assets/f49f9086-f95e-4cd0-8e40-fce43d465e2e)

2024-11-13 08:49 UTC, snoesberger commented
I tested this with an Extron SMP (2 inputs, channel A and B) and a pyCA (no input) and it worked as expected for both.

I only have a few minor comments:
- When no input is selected, the next button is greyed out and not clickable, but there is no indication for the user to know what is missing. Can you add some information to indicate that at least one channel needs to be selected? Perhaps a text message like the one that appears when you select an end date that is in the past?
- If the CA has inputs, the inputs field should also have a red star symbol like the other required fields.

Perhaps someone who has CAs from other vendors can have a look and see if this works well for them too?

2024-11-18 16:17 UTC, lkiesow commented
I'm wondering what our expectations for capture agents are for this.
Our documentation states that it's up to the agent to interpret whatever value they get.
Which seems to me like no selection would also be a valid option.

In that sense, we should at least test this with all commonly used agents before merging this:

- [ ] Extron SMP
- [ ] Adena Arec
- [ ] Epiphan Perl
- [ ] pyCA
- [ ] Galicaster *←(not sure if anyone is still using that)*

Or was this behavior already present in the old admin interface?

2024-11-18 23:35 UTC, gregorydlogan commented
@JamesUoM @NadiaUoM you guys still using Galicaster?

2024-11-19 10:37 UTC, NadiaUoM commented
Hi Greg,

Yes, we still use galicaster.

Thanks & Regards,
Nadia Malek.
From: Greg Logan ***@***.***>
Sent: 18 November 2024 23:35
To: opencast/opencast-admin-interface ***@***.***>
Cc: Nadia Malek ***@***.***>; Mention ***@***.***>
Subject: Re: [opencast/opencast-admin-interface] Preselect all capture agent inputs when scheduling new event (PR #979)


@JamesUoM [github.com]<https://urldefense.com/v3/__https:/github.com/JamesUoM__;!!PDiH4ENfjr2_Jw!AzI53ToNo0gESJRxIH9oIC99O4aSFwC0W_F-5-sJMrxvcefLcTqOI-0ksvoAeR8X1wwrZveF1spFqsmsQnUwHGuXSCBDbivd$> @NadiaUoM [github.com]<https://urldefense.com/v3/__https:/github.com/NadiaUoM__;!!PDiH4ENfjr2_Jw!AzI53ToNo0gESJRxIH9oIC99O4aSFwC0W_F-5-sJMrxvcefLcTqOI-0ksvoAeR8X1wwrZveF1spFqsmsQnUwHGuXSDswQyB0$> you guys still using Galicaster?

-
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.com/v3/__https:/github.com/opencast/opencast-admin-interface/pull/979*issuecomment-2484388788__;Iw!!PDiH4ENfjr2_Jw!AzI53ToNo0gESJRxIH9oIC99O4aSFwC0W_F-5-sJMrxvcefLcTqOI-0ksvoAeR8X1wwrZveF1spFqsmsQnUwHGuXSD4s4efZ$>, or unsubscribe [github.com]<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/BFC3B5YBSO7U6YHSBRJJBAD2BJ2TZAVCNFSM6AAAAABRTWWKAKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBUGM4DQNZYHA__;!!PDiH4ENfjr2_Jw!AzI53ToNo0gESJRxIH9oIC99O4aSFwC0W_F-5-sJMrxvcefLcTqOI-0ksvoAeR8X1wwrZveF1spFqsmsQnUwHGuXSKsgPZor$>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

2024-11-19 11:16 UTC, JamesUoM commented
... But we are going to move to pyCA by the next academic year.

James


--
------------------------------------------------------------------------
  James S. Perrin

  Media Technologies Team
  Office One, Kilburn Building,
  The University of Manchester
  Oxford Road, Manchester, M13 9PL

  e: ***@***.***
________________________________
From: NadiaUoM ***@***.***>
Sent: 19 November 2024 10:38
To: opencast/opencast-admin-interface ***@***.***>
Cc: James Perrin ***@***.***>; Mention ***@***.***>
Subject: Re: [opencast/opencast-admin-interface] Preselect all capture agent inputs when scheduling new event (PR #979)


Hi Greg,

Yes, we still use galicaster.

Thanks & Regards,
Nadia Malek.
From: Greg Logan ***@***.***>
Sent: 18 November 2024 23:35
To: opencast/opencast-admin-interface ***@***.***>
Cc: Nadia Malek ***@***.***>; Mention ***@***.***>
Subject: Re: [opencast/opencast-admin-interface] Preselect all capture agent inputs when scheduling new event (PR #979)


@JamesUoM [github.com]<https://urldefense.com/v3/__https:/github.com/JamesUoM__;!!PDiH4ENfjr2_Jw!AzI53ToNo0gESJRxIH9oIC99O4aSFwC0W_F-5-sJMrxvcefLcTqOI-0ksvoAeR8X1wwrZveF1spFqsmsQnUwHGuXSCBDbivd$> @NadiaUoM [github.com]<https://urldefense.com/v3/__https:/github.com/NadiaUoM__;!!PDiH4ENfjr2_Jw!AzI53ToNo0gESJRxIH9oIC99O4aSFwC0W_F-5-sJMrxvcefLcTqOI-0ksvoAeR8X1wwrZveF1spFqsmsQnUwHGuXSDswQyB0$> you guys still using Galicaster?

-
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.com/v3/__https:/github.com/opencast/opencast-admin-interface/pull/979*issuecomment-2484388788__;Iw!!PDiH4ENfjr2_Jw!AzI53ToNo0gESJRxIH9oIC99O4aSFwC0W_F-5-sJMrxvcefLcTqOI-0ksvoAeR8X1wwrZveF1spFqsmsQnUwHGuXSD4s4efZ$>, or unsubscribe [github.com]<https://urldefense.com/v3/__https:/github.com/notifications/unsubscribe-auth/BFC3B5YBSO7U6YHSBRJJBAD2BJ2TZAVCNFSM6AAAAABRTWWKAKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBUGM4DQNZYHA__;!!PDiH4ENfjr2_Jw!AzI53ToNo0gESJRxIH9oIC99O4aSFwC0W_F-5-sJMrxvcefLcTqOI-0ksvoAeR8X1wwrZveF1spFqsmsQnUwHGuXSKsgPZor$>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

—
Reply to this email directly, view it on GitHub [github.com]<https://urldefense.com/v3/__https://github.com/opencast/opencast-admin-interface/pull/979*issuecomment-2485322061__;Iw!!PDiH4ENfjr2_Jw!HXTOWJXAUFJpw0OYLvmzE3671_NUFzzN3mcPdPU4arwk_-3an4UEx5kfnOkfUR54E9DLwVYro-01s4a3e6x_idJOyD65dsGvCA$>, or unsubscribe [github.com]<https://urldefense.com/v3/__https://github.com/notifications/unsubscribe-auth/AAWQ6E7FXOW2DNYO2KEBB432BMIIZAVCNFSM6AAAAABRTWWKAKVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBVGMZDEMBWGE__;!!PDiH4ENfjr2_Jw!HXTOWJXAUFJpw0OYLvmzE3671_NUFzzN3mcPdPU4arwk_-3an4UEx5kfnOkfUR54E9DLwVYro-01s4a3e6x_idJOyD5zk2-pyg$>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-11-20 16:31 UTC, gregorydlogan commented
Can you guys take a quick poke and see if this change breaks things for you while you're still using GC?

2024-11-21 11:23 UTC, JamesUoM commented
> Can you guys take a quick poke and see if this change breaks things for you while you're still using GC?

Ok, though I doubt we'll still be using GC when we eventually deploy this code ;-)

2024-11-29 10:24 UTC, JamesUoM commented
> > Can you guys take a quick poke and see if this change breaks things for you while you're still using GC?
> 
> Ok, though I doubt we'll still be using GC when we eventually deploy this code ;-)

BTW I assume Zaragoza will be using GC

2024-11-29 11:33 UTC, JamesUoM commented
This will work fine with GC and matches what we have in the old Admin UI.

NOTE: GC can be configured to "hide" the inputs/tracks from OC and just returns `capture.device.names=defaults`  if a scheduler requests `capture.device.names=defaults` or `capture.device.names=` than all enabled tracks are recorded

2025-04-02 22:33 UTC, gregorydlogan commented
This doesn't seem to work for me.  I get the right UI elements, but nothing's selected?
[Screencast from 2025-04-02 16-32-53.webm](https://github.com/user-attachments/assets/4b09b034-7d20-4cdc-87c6-48495820add4)

2025-05-15 08:53 UTC, Arnei commented
Might be bugged due to a faulty merge. However, as it is unclear if we even want this feature at all, I'll abstain from working on the code for now.

2025-05-15 09:26 UTC, snoesberger commented
I'd still love to have this feature. Btw. the behavior was already like that in the old admin UI.

From an end user's point of view, this improves usability and saves clicks. For Extron devices, the default with no active input is not a valid config because at least one input must be selected to make a usable recording.
And I fear that there will be many support cases because users forget to activate an input and end up with an empty recording.

2025-06-18 13:39 UTC, snoesberger commented
The preselection of the inputs doesn't work anymore. I did plan a new event for an Extron SMP, the two inputs Channel A and Channel B were displayed but the checkboxes weren't preselected.

2025-10-21 18:06 UTC, gregorydlogan requested changes
Looks like the code underneath changed?

```
/home/greg/opencast/opencast-admin-interface/src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  627:15  error  'inputDevice' is never reassigned. Use 'const' instead  prefer-const
```

2025-11-14 19:38 UTC, gregorydlogan commented
```
/home/greg/opencast/opencast-admin-interface/src/components/events/partials/ModalTabsAndPages/NewSourcePage.tsx
  626:15  error  'inputDevice' is never reassigned. Use 'const' instead  prefer-const
```

2026-03-27 01:49 UTC, closed without merging